Repository OCA/reporting-engine, pull requests merged in 2019-10, with the labels that each got.

#321 [12.0][report_xlsx_helper] fix error message
  report_xlsx_helper/report/report_xlsx_abstract.py
Labels: approved

#322 [11.0][FIX] Report xlsx res_partner
  report_xlsx/report/report_partner_xlsx.py
Labels: approved, ready to merge

#327 [11.0][IMP] report_xlsx, make sure print_report_name works
  report_xlsx/controllers/main.py
Labels: approved

#335 [12.0][FIX] Report xlsx res_partner
  report_xlsx/report/report_partner_xlsx.py
Labels: approved

#259 report_xlsx: fix report context propagation on records
  report_xlsx/models/ir_report.py
  report_xlsx/report/report_xlsx.py
Labels: bug

#320 [10.0][ADD] Header and Footer configuration for XLSX report
  report_xlsx/README.rst
  report_xlsx/__manifest__.py
  report_xlsx/models/__init__.py
  report_xlsx/models/header_footer.py
  report_xlsx/models/ir_report.py
  report_xlsx/report/report_xlsx.py
  report_xlsx/security/ir.model.access.csv
  report_xlsx/tests/__init__.py
  report_xlsx/tests/test_header_footer.py
  report_xlsx/views/header_footer.xml
  report_xlsx/views/ir_report.xml
Labels: approved, needs review, ready to merge

#338 [10.0][FIX] report_xlsx: missing dependency
  report_xlsx/__manifest__.py
Labels: needs review
