Repository OCA/reporting-engine, pull requests merged in 2020-03, with the labels that each got.

#367 [13.0][MIG] report_csv
  report_csv/README.rst
  report_csv/__init__.py
  report_csv/__manifest__.py
  report_csv/controllers/__init__.py
  report_csv/controllers/main.py
  report_csv/demo/report.xml
  report_csv/i18n/report_csv.pot
  report_csv/models/__init__.py
  report_csv/models/ir_report.py
  report_csv/readme/CONTRIBUTORS.rst
  report_csv/readme/DESCRIPTION.rst
  report_csv/readme/USAGE.rst
  report_csv/report/__init__.py
  report_csv/report/report_csv.py
  report_csv/report/report_partner_csv.py
  report_csv/static/description/icon.png
  report_csv/static/description/index.html
  report_csv/static/src/js/report/qwebactionmanager.js
  report_csv/tests/__init__.py
  report_csv/tests/test_report.py
  report_csv/views/webclient_templates.xml
Labels: approved, ready to merge

#374 [13.0][MIG] report_qr
  .isort.cfg
  report_qr/README.rst
  report_qr/__init__.py
  report_qr/__manifest__.py
  report_qr/controllers/__init__.py
  report_qr/controllers/qr.py
  report_qr/i18n/report_qr.pot
  report_qr/models/__init__.py
  report_qr/models/ir_actions_report.py
  report_qr/readme/CONTRIBUTORS.rst
  report_qr/readme/DESCRIPTION.rst
  report_qr/readme/USAGE.rst
  report_qr/static/description/icon.png
  report_qr/static/description/index.html
  report_qr/static/description/new_qr.png
  report_qr/static/description/old_qr.png
  report_qr/tests/__init__.py
  report_qr/tests/test_report_qr.py
Labels: approved, ready to merge

#379 [13.0][MIG] report_qweb_pdf_fixed_column: Migration to 13.0
  report_qweb_pdf_fixed_column/README.rst
  report_qweb_pdf_fixed_column/__init__.py
  report_qweb_pdf_fixed_column/__manifest__.py
  report_qweb_pdf_fixed_column/i18n/report_qweb_pdf_fixed_column.pot
  report_qweb_pdf_fixed_column/readme/CONTRIBUTORS.rst
  report_qweb_pdf_fixed_column/readme/DESCRIPTION.rst
  report_qweb_pdf_fixed_column/readme/USAGE.rst
  report_qweb_pdf_fixed_column/static/description/icon.png
  report_qweb_pdf_fixed_column/static/description/index.html
  report_qweb_pdf_fixed_column/static/src/css/report_qweb_pdf_fixed_column.scss
  report_qweb_pdf_fixed_column/views/assets.xml
  setup/report_qweb_pdf_fixed_column/odoo/addons/report_qweb_pdf_fixed_column
  setup/report_qweb_pdf_fixed_column/setup.py
Labels: approved

#377 [IMP][12.0] bi_sql_editor : add action context
  bi_sql_editor/models/bi_sql_view.py
  bi_sql_editor/views/view_bi_sql_view.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#352 [12.0][ENH] sql view - allow group operator
  bi_sql_editor_aggregate/README.rst
  bi_sql_editor_aggregate/__init__.py
  bi_sql_editor_aggregate/__manifest__.py
  bi_sql_editor_aggregate/description/icon.png
  bi_sql_editor_aggregate/models/__init__.py
  bi_sql_editor_aggregate/models/bi_sql_view.py
  bi_sql_editor_aggregate/models/bi_sql_view_field.py
  bi_sql_editor_aggregate/models/ir_model.py
  bi_sql_editor_aggregate/views/view_bi_sql_view.xml
Labels: approved, bot is merging ⏳, ready to merge
