Repository OCA/reporting-engine, pull requests merged in 2020-06, with the labels that each got.

#411 [FIX] report_qweb_signer: reprint report crash
  report_qweb_signer/models/ir_actions_report.py
Labels: bot is merging ⏳

#351 [11.0][ENH] sql view - allow group operator
  bi_sql_editor_aggregate/README.rst
  bi_sql_editor_aggregate/__init__.py
  bi_sql_editor_aggregate/__manifest__.py
  bi_sql_editor_aggregate/description/icon.png
  bi_sql_editor_aggregate/models/__init__.py
  bi_sql_editor_aggregate/models/bi_sql_view.py
  bi_sql_editor_aggregate/models/bi_sql_view_field.py
  bi_sql_editor_aggregate/models/ir_model.py
  bi_sql_editor_aggregate/views/view_bi_sql_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#391 [12.0][FIX] bi_view_editor: window functions without ORDER BY clause do not have reliable behavior
  bi_view_editor/models/bve_view.py
  bi_view_editor/readme/USAGE.rst
  bi_view_editor/tests/test_bi_view.py
  bi_view_editor/views/bve_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#412 [FIX] bi_sql_editor: allow XML-RPC calls
  bi_sql_editor/models/bi_sql_view.py
Labels: approved, bot is merging ⏳

#394 [12.0][ADD] kpi_dashboard_bokeh
  kpi_dashboard_bokeh/README.rst
  kpi_dashboard_bokeh/__init__.py
  kpi_dashboard_bokeh/__manifest__.py
  kpi_dashboard_bokeh/demo/demo_dashboard.xml
  kpi_dashboard_bokeh/models/__init__.py
  kpi_dashboard_bokeh/models/kpi_kpi.py
  kpi_dashboard_bokeh/readme/CONFIGURE.rst
  kpi_dashboard_bokeh/readme/CONTRIBUTORS.rst
  kpi_dashboard_bokeh/readme/DESCRIPTION.rst
  kpi_dashboard_bokeh/static/description/icon.png
  kpi_dashboard_bokeh/static/description/index.html
  kpi_dashboard_bokeh/static/src/js/bokeh_widget.js
  kpi_dashboard_bokeh/static/src/xml/dashboard.xml
  kpi_dashboard_bokeh/views/webclient_templates.xml
Labels: approved, bot is merging ⏳, ready to merge
