Repository OCA/reporting-engine, pull requests merged in 2020-07, with the labels that each got.

#342 [11.0][MIG] report_qweb_txt to 11.0
  report_qweb_txt/README.rst
  report_qweb_txt/__init__.py
  report_qweb_txt/__manifest__.py
  report_qweb_txt/demo/report.xml
  report_qweb_txt/demo/res_users_report.xml
  report_qweb_txt/i18n/ca.po
  report_qweb_txt/i18n/da.po
  report_qweb_txt/i18n/de.po
  report_qweb_txt/i18n/el_GR.po
  report_qweb_txt/i18n/es.po
  report_qweb_txt/i18n/es_CO.po
  report_qweb_txt/i18n/fr.po
  report_qweb_txt/i18n/gl.po
  report_qweb_txt/i18n/hr.po
  report_qweb_txt/i18n/hr_HR.po
  report_qweb_txt/i18n/it.po
  report_qweb_txt/i18n/nb_NO.po
  report_qweb_txt/i18n/nl_NL.po
  report_qweb_txt/i18n/pl.po
  report_qweb_txt/i18n/pt.po
  report_qweb_txt/i18n/pt_BR.po
  report_qweb_txt/i18n/pt_PT.po
  report_qweb_txt/i18n/report_qweb_txt.pot
  report_qweb_txt/i18n/sl.po
  report_qweb_txt/i18n/tr.po
  report_qweb_txt/i18n/tr_TR.po
  report_qweb_txt/models/__init__.py
  report_qweb_txt/models/ir_actions_report.py
  report_qweb_txt/readme/CONTRIBUTORS.rst
  report_qweb_txt/readme/DESCRIPTION.rst
  report_qweb_txt/readme/USAGE.rst
  report_qweb_txt/static/description/icon.png
Labels: bot is merging ⏳, needs review

#416 [IMP] kpi_dashboard: Set history & Add compute on the fly & Show value on kpi form
  kpi_dashboard/models/kpi_dashboard.py
  kpi_dashboard/models/kpi_kpi.py
  kpi_dashboard/security/ir.model.access.csv
  kpi_dashboard/static/src/js/dashboard_controller.js
  kpi_dashboard/static/src/js/dashboard_renderer.js
  kpi_dashboard/static/src/js/field_widget.js
  kpi_dashboard/static/src/js/widget/abstract_widget.js
  kpi_dashboard/static/src/xml/dashboard.xml
  kpi_dashboard/tests/test_formula.py
  kpi_dashboard/views/kpi_dashboard.xml
  kpi_dashboard/views/kpi_kpi.xml
  kpi_dashboard/views/webclient_templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#406 [13.0][MIG] report_qweb_element_page_visibility
  report_qweb_element_page_visibility/README.rst
  report_qweb_element_page_visibility/__init__.py
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/i18n/report_qweb_element_page_visibility.pot
  report_qweb_element_page_visibility/readme/CONTRIBUTORS.rst
  report_qweb_element_page_visibility/readme/DESCRIPTION.rst
  report_qweb_element_page_visibility/readme/USAGE.rst
  report_qweb_element_page_visibility/static/description/icon.png
  report_qweb_element_page_visibility/static/description/index.html
  report_qweb_element_page_visibility/views/layouts.xml
  setup/report_qweb_element_page_visibility/odoo/addons/report_qweb_element_page_visibility
  setup/report_qweb_element_page_visibility/setup.py
Labels: approved, bot is merging ⏳
