Repository OCA/reporting-engine, pull requests merged in 2020-05, with the labels that each got.

#395 [12.0][ADD] kpi_dashboard_altair
  kpi_dashboard_altair/README.rst
  kpi_dashboard_altair/__init__.py
  kpi_dashboard_altair/__manifest__.py
  kpi_dashboard_altair/demo/demo_dashboard_altair.xml
  kpi_dashboard_altair/models/__init__.py
  kpi_dashboard_altair/models/kpi_kpi.py
  kpi_dashboard_altair/readme/CONFIGURE.rst
  kpi_dashboard_altair/readme/CONTRIBUTORS.rst
  kpi_dashboard_altair/readme/DESCRIPTION.rst
  kpi_dashboard_altair/static/description/icon.png
  kpi_dashboard_altair/static/description/index.html
  kpi_dashboard_altair/static/lib/vega/vega-embed.min.js
  kpi_dashboard_altair/static/lib/vega/vega-lite.min.js
  kpi_dashboard_altair/static/lib/vega/vega.min.js
  kpi_dashboard_altair/static/src/js/altair_widget.js
  kpi_dashboard_altair/static/src/xml/dashboard.xml
  kpi_dashboard_altair/views/webclient_templates.xml
  requirements.txt
Labels: approved, bot is merging ⏳, ready to merge

#398 12.0 IMP kpi_dashborad: set ondelete on dash_id
  kpi_dashboard/models/kpi_dashboard.py
  kpi_dashboard_altair/models/kpi_kpi.py
Labels: approved, bot is merging ⏳

#399 IMP kpi_dashb_altair: doc
  kpi_dashboard_altair/README.rst
  kpi_dashboard_altair/__manifest__.py
  kpi_dashboard_altair/readme/CONFIGURE.rst
  kpi_dashboard_altair/readme/USAGE.rst
  kpi_dashboard_altair/static/description/config.png
  kpi_dashboard_altair/static/description/graph.png
  kpi_dashboard_altair/static/description/index.html
Labels: approved, bot is merging ⏳

#355 [12.0][ADD] report_async
  oca_dependencies.txt
  report_async/__init__.py
  report_async/__manifest__.py
  report_async/data/mail_template.xml
  report_async/demo/report_async_demo.xml
  report_async/models/__init__.py
  report_async/models/ir_report.py
  report_async/models/report_async.py
  report_async/readme/CONTRIBUTORS.rst
  report_async/readme/DESCRIPTION.rst
  report_async/readme/USAGE.rst
  report_async/security/ir.model.access.csv
  report_async/security/ir_rule.xml
  report_async/static/description/icon.png
  report_async/static/description/index.html
  report_async/tests/__init__.py
  report_async/tests/test_report_async.py
  report_async/views/report_async.xml
  report_async/wizard/__init__.py
  report_async/wizard/print_report_wizard.py
  report_async/wizard/print_report_wizard.xml
Labels: bot is merging ⏳
