Repository OCA/reporting-engine, pull requests merged in 2020-10, with the labels that each got.

#440 [FIX] Fix 'installable' syntax in manifest file
  report_qweb_pdf_watermark/__manifest__.py
Labels: approved, bot is merging ⏳

#439 [FIX] report_qr: New QR Library does not contain the old failure
  report_qr/models/ir_actions_report.py
Labels: approved, bot is merging ⏳, ready to merge

#448 [12.0][FIX] report_qweb_signer: Fix website
  report_qweb_signer/__manifest__.py
Labels: bot is merging ⏳
