Repository OCA/reporting-engine, pull requests merged in 2021-12, with the labels that each got.

#303 add default filetype to prevent error
  report_py3o/models/ir_actions_report.py
Labels: bot is merging ⏳

#490 [FIX] report_py3o: wrong extension for .odt files in zip
  report_py3o/models/py3o_report.py
Labels: bot is merging ⏳

#554 [15.0][MIG] report_xlsx
  report_xlsx/README.rst
  report_xlsx/__init__.py
  report_xlsx/__manifest__.py
  report_xlsx/controllers/__init__.py
  report_xlsx/controllers/main.py
  report_xlsx/demo/report.xml
  report_xlsx/i18n/de.po
  report_xlsx/i18n/es.po
  report_xlsx/i18n/fr.po
  report_xlsx/i18n/hr.po
  report_xlsx/i18n/hr_HR.po
  report_xlsx/i18n/it.po
  report_xlsx/i18n/nl_NL.po
  report_xlsx/i18n/pt.po
  report_xlsx/i18n/pt_PT.po
  report_xlsx/i18n/report_xlsx.pot
  report_xlsx/i18n/sv.po
  report_xlsx/i18n/tr.po
  report_xlsx/models/__init__.py
  report_xlsx/models/ir_report.py
  report_xlsx/readme/CONTRIBUTORS.rst
  report_xlsx/readme/DESCRIPTION.rst
  report_xlsx/readme/INSTALL.rst
  report_xlsx/readme/USAGE.rst
  report_xlsx/report/__init__.py
  report_xlsx/report/report_abstract_xlsx.py
  report_xlsx/report/report_partner_xlsx.py
  report_xlsx/static/description/icon.png
  report_xlsx/static/description/index.html
  report_xlsx/static/src/js/report/action_manager_report.esm.js
  report_xlsx/tests/__init__.py
  report_xlsx/tests/test_report.py
  requirements.txt
  setup/report_xlsx/odoo/addons/report_xlsx
  setup/report_xlsx/setup.py
Labels: approved

#555 [14.0][FW] report_xlsx: multiple ports from 12.0, 13.0
  report_xlsx/report/report_partner_xlsx.py
  report_xlsx/static/src/js/report/action_manager_report.js
Labels: bug, approved, bot is merging ⏳

#558 [REF] bi_sql_editor : add maintainers
  bi_sql_editor/__manifest__.py
Labels: approved, bot is merging ⏳

#496 [REF] bi_sql_editor : move function into abstract module
  bi_sql_editor/models/bi_sql_view.py
Labels: bot is merging ⏳

#519 [IMP] bi_sql_editor : conserve cron settings, when setting materialized view to draft ; Set correct default values for cron and enable it
  bi_sql_editor/models/bi_sql_view.py
  bi_sql_editor/tests/test_bi_sql_view.py
Labels: bot is merging ⏳

#413 12.0 imp bi sql editor ui
  bi_sql_editor/models/bi_sql_view.py
  bi_sql_editor/models/bi_sql_view_field.py
  bi_sql_editor/views/view_bi_sql_view.xml
Labels: bot is merging ⏳

#567 [IMP][12.0] bi_sql_editor : use ace widget
  bi_sql_editor/views/view_bi_sql_view.xml
Labels: approved, bot is merging ⏳
