Repository OCA/reporting-engine, pull requests merged in 2021-02, with the labels that each got.

#459 [12.0][ADD] report_qweb_encrypt
  report_qweb_encrypt/README.rst
  report_qweb_encrypt/__init__.py
  report_qweb_encrypt/__manifest__.py
  report_qweb_encrypt/controllers/__init__.py
  report_qweb_encrypt/controllers/main.py
  report_qweb_encrypt/models/__init__.py
  report_qweb_encrypt/models/ir_actions_report.py
  report_qweb_encrypt/readme/CONTRIBUTORS.rst
  report_qweb_encrypt/readme/DESCRIPTION.rst
  report_qweb_encrypt/readme/USAGE.rst
  report_qweb_encrypt/static/description/icon.png
  report_qweb_encrypt/static/src/js/report/action_manager_report.js
  report_qweb_encrypt/templates/assets.xml
  report_qweb_encrypt/tests/__init__.py
  report_qweb_encrypt/tests/test_report_qweb_encrypt.py
  report_qweb_encrypt/views/ir_actions_report.xml
Labels: approved, bot is merging ⏳, ready to merge

#437 [13.0][MIG] report_context
  report_context/README.rst
  report_context/__init__.py
  report_context/__manifest__.py
  report_context/controllers/__init__.py
  report_context/controllers/main.py
  report_context/data/config_parameter.xml
  report_context/i18n/report_context.pot
  report_context/models/__init__.py
  report_context/models/ir_actions_report.py
  report_context/readme/CONTRIBUTORS.rst
  report_context/readme/DESCRIPTION.rst
  report_context/readme/USAGE.rst
  report_context/static/description/icon.png
  report_context/static/description/index.html
  report_context/tests/__init__.py
  report_context/tests/test_report_context.py
  report_context/views/ir_actions_report.xml
  setup/report_context/odoo/addons/report_context
  setup/report_context/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#482 [13.0][FIX] report_xlsx_helper: force Libreoffice to recompute formulas
  report_xlsx_helper/report/report_xlsx_abstract.py
Labels: approved, bot is merging ⏳

#464 [14.0][MIG] report_qweb_encrypt
  .travis.yml
  report_qweb_encrypt/README.rst
  report_qweb_encrypt/__init__.py
  report_qweb_encrypt/__manifest__.py
  report_qweb_encrypt/controllers/__init__.py
  report_qweb_encrypt/controllers/main.py
  report_qweb_encrypt/models/__init__.py
  report_qweb_encrypt/models/ir_actions_report.py
  report_qweb_encrypt/readme/CONTRIBUTORS.rst
  report_qweb_encrypt/readme/DESCRIPTION.rst
  report_qweb_encrypt/readme/USAGE.rst
  report_qweb_encrypt/static/description/icon.png
  report_qweb_encrypt/static/src/js/report/action_manager_report.js
  report_qweb_encrypt/templates/assets.xml
  report_qweb_encrypt/tests/__init__.py
  report_qweb_encrypt/tests/test_report_qweb_encrypt.py
  report_qweb_encrypt/views/ir_actions_report.xml
  setup/report_qweb_encrypt/odoo/addons/report_qweb_encrypt
  setup/report_qweb_encrypt/setup.py
Labels: approved, bot is merging ⏳

#471 [13.0][FIX]report_xlsx multi-company bug
  report_xlsx/static/src/js/report/action_manager_report.js
Labels: bot is merging ⏳
