Repository OCA/reporting-engine, pull requests merged in 2021-04, with the labels that each got.

#497 [13.0][IMP] base_comment_template: Add function to get_comment_template records
  base_comment_template/models/base_comment_template.py
Labels: approved, bot is merging ⏳

#499 [13.0][FIX] base_comment_template: Fix tests: test_company_general_template
  base_comment_template/readme/CONTRIBUTORS.rst
  base_comment_template/tests/test_base_comment_template.py
Labels: approved, bot is merging ⏳

#478 [14.0] mig report qweb pdf watermark
  .travis.yml
  report_qweb_pdf_watermark/README.rst
  report_qweb_pdf_watermark/__init__.py
  report_qweb_pdf_watermark/__manifest__.py
  report_qweb_pdf_watermark/demo/report.xml
  report_qweb_pdf_watermark/i18n/ca.po
  report_qweb_pdf_watermark/i18n/da.po
  report_qweb_pdf_watermark/i18n/de.po
  report_qweb_pdf_watermark/i18n/el_GR.po
  report_qweb_pdf_watermark/i18n/es.po
  report_qweb_pdf_watermark/i18n/es_CO.po
  report_qweb_pdf_watermark/i18n/fr.po
  report_qweb_pdf_watermark/i18n/gl.po
  report_qweb_pdf_watermark/i18n/hr.po
  report_qweb_pdf_watermark/i18n/hr_HR.po
  report_qweb_pdf_watermark/i18n/it.po
  report_qweb_pdf_watermark/i18n/nb_NO.po
  report_qweb_pdf_watermark/i18n/nl_NL.po
  report_qweb_pdf_watermark/i18n/pl.po
  report_qweb_pdf_watermark/i18n/pt.po
  report_qweb_pdf_watermark/i18n/pt_BR.po
  report_qweb_pdf_watermark/i18n/pt_PT.po
  report_qweb_pdf_watermark/i18n/report_qweb_pdf_watermark.pot
  report_qweb_pdf_watermark/i18n/sl.po
  report_qweb_pdf_watermark/i18n/tr.po
  report_qweb_pdf_watermark/i18n/tr_TR.po
  report_qweb_pdf_watermark/models/__init__.py
  report_qweb_pdf_watermark/models/report.py
  report_qweb_pdf_watermark/readme/CONTRIBUTORS.rst
  report_qweb_pdf_watermark/readme/DESCRIPTION.rst
  report_qweb_pdf_watermark/readme/HISTORY.rst
  report_qweb_pdf_watermark/readme/INSTALL.rst
  report_qweb_pdf_watermark/readme/ROADMAP.rst
  report_qweb_pdf_watermark/readme/USAGE.rst
  report_qweb_pdf_watermark/static/description/icon.png
  report_qweb_pdf_watermark/static/description/index.html
  report_qweb_pdf_watermark/static/src/css/report_qweb_pdf_watermark.css
  report_qweb_pdf_watermark/tests/__init__.py
  report_qweb_pdf_watermark/tests/test_report_qweb_pdf_watermark.py
  report_qweb_pdf_watermark/views/ir_actions_report_xml.xml
  report_qweb_pdf_watermark/views/layout_templates.xml
  requirements.txt
  setup/report_qweb_pdf_watermark/odoo/addons/report_qweb_pdf_watermark
  setup/report_qweb_pdf_watermark/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#501 [13.0][FIX] base_comment_template: Change domain in rule according to company
  base_comment_template/security/security.xml
Labels: bot is merging ⏳

#489 [FIX] report_xml: add context to /report/download
  report_xml/controllers/main.py
Labels: approved, bot is merging ⏳

#447 [MIG] kpi_dashboard: Migration to 14.0
  kpi_dashboard/README.rst
  kpi_dashboard/__init__.py
  kpi_dashboard/__manifest__.py
  kpi_dashboard/demo/demo_dashboard.xml
  kpi_dashboard/i18n/kpi_dashboard.pot
  kpi_dashboard/models/__init__.py
  kpi_dashboard/models/ir_actions_act_window_view.py
  kpi_dashboard/models/ir_ui_view.py
  kpi_dashboard/models/kpi_dashboard.py
  kpi_dashboard/models/kpi_kpi.py
  kpi_dashboard/readme/CONFIGURE.rst
  kpi_dashboard/readme/CONTRIBUTORS.rst
  kpi_dashboard/readme/DESCRIPTION.rst
  kpi_dashboard/security/ir.model.access.csv
  kpi_dashboard/security/security.xml
  kpi_dashboard/static/description/icon.png
  kpi_dashboard/static/description/index.html
  kpi_dashboard/static/lib/gauge/GaugeMeter.js
  kpi_dashboard/static/lib/gridster/jquery.dsmorse-gridster.min.css
  kpi_dashboard/static/lib/gridster/jquery.dsmorse-gridster.min.js
  kpi_dashboard/static/lib/nvd3/d3.v3.js
  kpi_dashboard/static/lib/nvd3/nv.d3.css
  kpi_dashboard/static/lib/nvd3/nv.d3.js
  kpi_dashboard/static/src/js/dashboard_controller.js
  kpi_dashboard/static/src/js/dashboard_model.js
  kpi_dashboard/static/src/js/dashboard_renderer.js
  kpi_dashboard/static/src/js/dashboard_view.js
  kpi_dashboard/static/src/js/field_widget.js
  kpi_dashboard/static/src/js/lib/nvd3.js
  kpi_dashboard/static/src/js/widget/abstract_widget.js
  kpi_dashboard/static/src/js/widget/counter_widget.js
  kpi_dashboard/static/src/js/widget/graph_widget.js
  kpi_dashboard/static/src/js/widget/integer_widget.js
  kpi_dashboard/static/src/js/widget/meter_widget.js
  kpi_dashboard/static/src/js/widget/number_widget.js
  kpi_dashboard/static/src/js/widget/text_widget.js
  kpi_dashboard/static/src/js/widget_registry.js
  kpi_dashboard/static/src/scss/kpi_dashboard.scss
  kpi_dashboard/static/src/xml/dashboard.xml
  kpi_dashboard/templates/assets.xml
  kpi_dashboard/tests/__init__.py
  kpi_dashboard/tests/test_formula.py
  kpi_dashboard/tests/test_kpi_dashboard.py
  kpi_dashboard/views/kpi_dashboard.xml
  kpi_dashboard/views/kpi_kpi.xml
  kpi_dashboard/views/kpi_menu.xml
  kpi_dashboard/wizards/__init__.py
  kpi_dashboard/wizards/kpi_dashboard_menu.py
  kpi_dashboard/wizards/kpi_dashboard_menu.xml
Labels: approved, bot is merging ⏳, ready to merge

#488 [FIX] report_py3o: add context to /report/download
  report_py3o/controllers/main.py
Labels: approved, bot is merging ⏳

#503 [IMP] update dotfiles
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳, enhancement
