Repository OCA/reporting-engine, pull requests merged in 2021-11, with the labels that each got.

#483 [14.0][FIX] report_xlsx_helper: force Libreoffice to recompute formulas
  report_xlsx_helper/report/report_xlsx_abstract.py
Labels: approved, bot is merging ⏳

#547 [FIX] report_xlsx: correctly handle exceptions, when generating report
  report_xlsx/controllers/main.py
  report_xlsx/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#455 [FIX] bi_sql_editor : handle correctly translation for action name
  bi_sql_editor/models/bi_sql_view.py
Labels: approved, ready to merge, bot is merging ⏳

#526 [14.0] [MIG] report_qr
  report_qr/README.rst
  report_qr/__init__.py
  report_qr/__manifest__.py
  report_qr/controllers/__init__.py
  report_qr/controllers/qr.py
  report_qr/i18n/report_qr.pot
  report_qr/models/__init__.py
  report_qr/models/ir_actions_report.py
  report_qr/readme/CONTRIBUTORS.rst
  report_qr/readme/DESCRIPTION.rst
  report_qr/readme/USAGE.rst
  report_qr/static/description/icon.png
  report_qr/static/description/index.html
  report_qr/static/description/new_qr.png
  report_qr/static/description/old_qr.png
  report_qr/tests/__init__.py
  report_qr/tests/test_report_qr.py
  setup/report_qr/odoo/addons/report_qr
  setup/report_qr/setup.py
Labels: approved, ready to merge, bot is merging ⏳
