Repository OCA/reporting-engine, pull requests merged in 2021-05, with the labels that each got.

#422 [10.0] backport report_csv from 11.0
  report_csv/README.rst
  report_csv/__init__.py
  report_csv/__manifest__.py
  report_csv/controllers/__init__.py
  report_csv/controllers/main.py
  report_csv/demo/report.xml
  report_csv/i18n/report_csv.pot
  report_csv/models/__init__.py
  report_csv/models/ir_actions_report_xml.py
  report_csv/models/report.py
  report_csv/report/__init__.py
  report_csv/report/report_csv.py
  report_csv/report/report_partner_csv.py
  report_csv/static/description/icon.png
  report_csv/static/src/js/report/qwebactionmanager.js
  report_csv/tests/__init__.py
  report_csv/tests/test_report.py
  report_csv/views/webclient_templates.xml
  requirements.txt
  setup/report_csv/odoo/__init__.py
  setup/report_csv/odoo/addons/__init__.py
  setup/report_csv/odoo/addons/report_csv
  setup/report_csv/setup.py
Labels: approved, bot is merging ⏳

#504 [13.0][IMP] base_comment_template: Refactor code and convert to Many2Many
  base_comment_template/__manifest__.py
  base_comment_template/migrations/13.0.1.0.0/pre-migration.py
  base_comment_template/migrations/13.0.2.0.0/pre-migration.py
  base_comment_template/models/__init__.py
  base_comment_template/models/base_comment_template.py
  base_comment_template/models/comment_template.py
  base_comment_template/models/res_partner.py
  base_comment_template/tests/test_base_comment_template.py
  base_comment_template/views/base_comment_template_view.xml
  base_comment_template/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#508 [FIX] Define search view arch as unicode to make it possible to use non-ascii field descriptions
  bi_sql_editor/models/bi_sql_view.py
Labels: approved, bot is merging ⏳

#454 [12.0][IMP][report_qr] Allow setting proposed filename
  report_qr/controllers/qr.py
  report_qr/readme/USAGE.rst
Labels: approved, bot is merging ⏳, ready to merge

#500 [14.0][IMP] base_comment_template: Include changes from 13.0
  base_comment_template/README.rst
  base_comment_template/__manifest__.py
  base_comment_template/i18n/base_comment_template.pot
  base_comment_template/i18n/es.po
  base_comment_template/migrations/14.0.2.0.0/post-migration.py
  base_comment_template/migrations/14.0.2.0.0/pre-migration.py
  base_comment_template/models/__init__.py
  base_comment_template/models/base_comment_template.py
  base_comment_template/models/comment.py
  base_comment_template/models/comment_template.py
  base_comment_template/models/ir_model.py
  base_comment_template/models/res_partner.py
  base_comment_template/readme/CONFIGURE.rst
  base_comment_template/readme/CONTRIBUTORS.rst
  base_comment_template/readme/DESCRIPTION.rst
  base_comment_template/readme/USAGE.rst
  base_comment_template/security/ir.model.access.csv
  base_comment_template/security/security.xml
  base_comment_template/static/description/index.html
  base_comment_template/tests/fake_models.py
  base_comment_template/tests/test_base_comment_template.py
  base_comment_template/views/base_comment_template_view.xml
  base_comment_template/views/res_partner_view.xml
Labels: bot is merging ⏳

#509 [14.0][FIX] base_comment_template: Filter domain correctly
  base_comment_template/models/comment_template.py
Labels: approved, bot is merging ⏳

#512 [13.0][FIX] base_comment_template: Filter domain correctly
  base_comment_template/models/comment_template.py
Labels: approved, bot is merging ⏳

#475 [MIG] report_qweb_parameter: Migration to 14.0
  report_qweb_parameter/README.rst
  report_qweb_parameter/__init__.py
  report_qweb_parameter/__manifest__.py
  report_qweb_parameter/demo/test_report_field_length.xml
  report_qweb_parameter/i18n/es.po
  report_qweb_parameter/i18n/fr.po
  report_qweb_parameter/i18n/it.po
  report_qweb_parameter/i18n/pt.po
  report_qweb_parameter/i18n/report_qweb_parameter.pot
  report_qweb_parameter/models/__init__.py
  report_qweb_parameter/models/ir_qweb.py
  report_qweb_parameter/readme/CONTRIBUTORS.rst
  report_qweb_parameter/readme/DESCRIPTION.rst
  report_qweb_parameter/readme/USAGE.rst
  report_qweb_parameter/static/description/icon.png
  report_qweb_parameter/static/description/index.html
  report_qweb_parameter/tests/__init__.py
  report_qweb_parameter/tests/test_report_qweb_parameter.py
  setup/report_qweb_parameter/odoo/addons/report_qweb_parameter
  setup/report_qweb_parameter/setup.py
Labels: approved, bot is merging ⏳, ready to merge
