Repository OCA/reporting-engine, pull requests merged in 2022-02, with the labels that each got.

#583 [15.0][FIX] bi_sql_editor: fix typo
  bi_sql_editor/models/bi_sql_view_field.py
Labels: approved, bot is merging ⏳

#582 [15.0][MIG] sql_export_excel: Migration to 15.0
  requirements.txt
  setup/sql_export_excel/odoo/addons/sql_export_excel
  setup/sql_export_excel/setup.py
  sql_export_excel/README.rst
  sql_export_excel/__init__.py
  sql_export_excel/__manifest__.py
  sql_export_excel/i18n/sql_export_excel.pot
  sql_export_excel/models/__init__.py
  sql_export_excel/models/sql_export.py
  sql_export_excel/readme/CONFIGURE.rst
  sql_export_excel/readme/CONTRIBUTORS.rst
  sql_export_excel/readme/DESCRIPTION.rst
  sql_export_excel/static/description/icon.png
  sql_export_excel/static/description/index.html
  sql_export_excel/tests/__init__.py
  sql_export_excel/tests/test_sql_query_excel.py
  sql_export_excel/views/sql_export_view.xml
Labels: approved, migration, bot is merging ⏳

#587 [FIX] report_xlsx running report in su mode
  report_xlsx/models/ir_report.py
Labels: needs review, approved, bot is merging ⏳

#588 [15.0][PORT] 587 from 14.0
  report_xlsx/models/ir_report.py
Labels: approved, bot is merging ⏳

#584 [MIG] report_xlsx_helper: migration to 15.0
  report_xlsx_helper/README.rst
  report_xlsx_helper/__init__.py
  report_xlsx_helper/__manifest__.py
  report_xlsx_helper/controllers/__init__.py
  report_xlsx_helper/controllers/main.py
  report_xlsx_helper/i18n/es.po
  report_xlsx_helper/i18n/report_xlsx_helper.pot
  report_xlsx_helper/models/__init__.py
  report_xlsx_helper/models/ir_actions_report.py
  report_xlsx_helper/readme/CONTRIBUTORS.rst
  report_xlsx_helper/readme/DESCRIPTION.rst
  report_xlsx_helper/readme/INSTALL.rst
  report_xlsx_helper/readme/USAGE.rst
  report_xlsx_helper/report/__init__.py
  report_xlsx_helper/report/report_xlsx_abstract.py
  report_xlsx_helper/report/report_xlsx_format.py
  report_xlsx_helper/report/test_partner_report_xlsx.py
  report_xlsx_helper/static/description/icon.png
  report_xlsx_helper/static/description/index.html
  report_xlsx_helper/tests/__init__.py
  report_xlsx_helper/tests/test_report_xlsx_helper.py
  setup/report_xlsx_helper/odoo/addons/report_xlsx_helper
  setup/report_xlsx_helper/setup.py
Labels: approved, migration, bot is merging ⏳
