Repository OCA/reporting-engine, pull requests merged in 2022-04, with the labels that each got.

#610 [15.0][FIX]report_xlsx: development status to mature
  report_xlsx/__manifest__.py
Labels: bot is merging ⏳

#429 [13.0][MIG] report_async
  oca_dependencies.txt
  report_async/README.rst
  report_async/__init__.py
  report_async/__manifest__.py
  report_async/data/mail_template.xml
  report_async/demo/report_async_demo.xml
  report_async/i18n/report_async.pot
  report_async/models/__init__.py
  report_async/models/ir_report.py
  report_async/models/report_async.py
  report_async/readme/CONTRIBUTORS.rst
  report_async/readme/DESCRIPTION.rst
  report_async/readme/USAGE.rst
  report_async/security/ir.model.access.csv
  report_async/security/ir_rule.xml
  report_async/static/description/icon.png
  report_async/static/description/index.html
  report_async/tests/__init__.py
  report_async/tests/test_report_async.py
  report_async/views/report_async.xml
  report_async/wizard/__init__.py
  report_async/wizard/print_report_wizard.py
  report_async/wizard/print_report_wizard.xml
  setup/report_async/odoo/addons/report_async
  setup/report_async/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#572 [IMP] bi_sql_editor : conserve cron settings, when setting materialized view to draft ; Set correct default values for cron and enable it
  bi_sql_editor/__manifest__.py
  bi_sql_editor/models/bi_sql_view.py
Labels: approved, ready to merge, bot is merging ⏳

#613 [14.0][IMP] report_xlsx_helper: Promote to mature
  report_xlsx_helper/__manifest__.py
Labels: needs review, bot is merging ⏳

#614 [IMP] report_xml: Promote to Stable
  report_xml/__manifest__.py
Labels: bot is merging ⏳

#617 [14.0][IMP] report_xml: Promote to Stable
  report_xml/__manifest__.py
Labels: bot is merging ⏳

#618 [15.0][IMP] report_xml: Promote to Stable
  report_xml/__manifest__.py
Labels: bot is merging ⏳

#616 Port Commits from 13.0
  report_py3o/__manifest__.py
  report_qweb_signer/__manifest__.py
  report_qweb_signer/models/ir_actions_report.py
Labels: bot is merging ⏳

#575 [IMP] kpi_dashboard: Allow to set a specific context for a KPI
  kpi_dashboard/models/kpi_dashboard.py
  kpi_dashboard/views/kpi_dashboard.xml
Labels: approved, bot is merging ⏳

#506 [MIG] kpi_dashboard_bokeh: Migration to 14.0
  kpi_dashboard_bokeh/README.rst
  kpi_dashboard_bokeh/__init__.py
  kpi_dashboard_bokeh/__manifest__.py
  kpi_dashboard_bokeh/demo/demo_dashboard.xml
  kpi_dashboard_bokeh/i18n/kpi_dashboard_bokeh.pot
  kpi_dashboard_bokeh/models/__init__.py
  kpi_dashboard_bokeh/models/kpi_kpi.py
  kpi_dashboard_bokeh/readme/CONFIGURE.rst
  kpi_dashboard_bokeh/readme/CONTRIBUTORS.rst
  kpi_dashboard_bokeh/readme/DESCRIPTION.rst
  kpi_dashboard_bokeh/static/description/icon.png
  kpi_dashboard_bokeh/static/description/index.html
  kpi_dashboard_bokeh/static/src/js/bokeh_widget.js
  kpi_dashboard_bokeh/static/src/xml/dashboard.xml
  kpi_dashboard_bokeh/views/webclient_templates.xml
  oca_dependencies.txt
  setup/kpi_dashboard_bokeh/odoo/addons/kpi_dashboard_bokeh
  setup/kpi_dashboard_bokeh/setup.py
Labels: bot is merging ⏳
