Repository OCA/reporting-engine, pull requests merged in 2022-10, with the labels that each got.

#453 [13.0][MIG] - migration report_substitute
  report_substitute/README.rst
  report_substitute/__init__.py
  report_substitute/__manifest__.py
  report_substitute/demo/action_report.xml
  report_substitute/i18n/report_substitute.pot
  report_substitute/models/__init__.py
  report_substitute/models/ir_actions_report.py
  report_substitute/models/ir_actions_report_substitution_rule.py
  report_substitute/models/mail_thread.py
  report_substitute/readme/CONTRIBUTORS.rst
  report_substitute/readme/DESCRIPTION.rst
  report_substitute/readme/ROADMAP.rst
  report_substitute/readme/USAGE.rst
  report_substitute/security/ir_actions_report_substitution_rule.xml
  report_substitute/static/description/icon.png
  report_substitute/static/description/index.html
  report_substitute/static/src/js/action_manager.js
  report_substitute/tests/__init__.py
  report_substitute/tests/test_report_substitute.py
  report_substitute/views/assets_backend.xml
  report_substitute/views/ir_actions_report.xml
  report_substitute/wizards/__init__.py
  report_substitute/wizards/mail_compose_message.py
  setup/report_substitute/odoo/addons/report_substitute
  setup/report_substitute/setup.py
Labels: approved, bot is merging ⏳, stale

#561 [13.0] [IMP] bi_sql_editor - server actions integration
  bi_sql_editor_server_actions/__init__.py
  bi_sql_editor_server_actions/__manifest__.py
  bi_sql_editor_server_actions/models/__init__.py
  bi_sql_editor_server_actions/models/bi_sql_view.py
  bi_sql_editor_server_actions/models/ir_actions_server.py
  bi_sql_editor_server_actions/readme/CONTRIBUTORS.rst
  bi_sql_editor_server_actions/readme/DESCRIPTION.rst
  bi_sql_editor_server_actions/tests/__init__.py
  bi_sql_editor_server_actions/tests/test_bi_sql_view_server_action.py
  bi_sql_editor_server_actions/views/ir_actions_server_view.xml
  bi_sql_editor_server_actions/views/view_bi_sql_view.xml
  setup/bi_sql_editor_server_actions/odoo/addons/bi_sql_editor_server_actions
  setup/bi_sql_editor_server_actions/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#656 [14.0][FIX] base_comment_template: fixup iter wiz record
  base_comment_template/wizard/base_comment_template_preview.py
Labels: bot is merging ⏳

#611 [IMP] report_async 14.0
  report_async/README.rst
  report_async/__manifest__.py
  report_async/data/mail_template.xml
  report_async/models/__init__.py
  report_async/models/ir_report.py
  report_async/models/queue_job.py
  report_async/models/report_async.py
  report_async/readme/CONTRIBUTORS.rst
  report_async/readme/USAGE.rst
  report_async/static/description/index.html
  report_async/static/description/sample.gif
  report_async/static/src/js/components/action_menus.js
  report_async/static/src/tests/report_async_tests.js
  report_async/static/src/xml/report_async.xml
  report_async/views/assets.xml
  report_async/views/ir_actions_report.xml
  report_qweb_encrypt/static/src/js/report/action_manager_report.js
Labels: approved, bot is merging ⏳

#533 [13.0] [IMP] report_qweb_signer: allowed reports on certificate
  report_qweb_signer/README.rst
  report_qweb_signer/models/ir_actions_report.py
  report_qweb_signer/models/report_certificate.py
  report_qweb_signer/readme/ROADMAP.rst
  report_qweb_signer/views/report_certificate_view.xml
Labels: bot is merging ⏳, stale

#668 [14.0] [IMP] report_qweb_signer: allowed reports on certificate
  report_qweb_signer/README.rst
  report_qweb_signer/models/ir_actions_report.py
  report_qweb_signer/models/report_certificate.py
  report_qweb_signer/readme/ROADMAP.rst
  report_qweb_signer/views/report_certificate_view.xml
Labels: approved, bot is merging ⏳

#674 [14.0][FIX] report_qweb_signer: Fix TypeError
  report_qweb_signer/models/ir_actions_report.py
  report_qweb_signer/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳
