Repository OCA/reporting-engine, pull requests merged in 2023-07, with the labels that each got.

#701 [14.0][report_qweb_element_page_visibility][IMP] - use display for element visibility
  report_qweb_element_page_visibility/views/layouts.xml
Labels: approved, bot is merging ⏳, no stale

#702 [15.0][report_qweb_element_page_visibility][IMP] - use display for element visibility
  report_qweb_element_page_visibility/views/layouts.xml
Labels: approved, bot is merging ⏳

#765 Update bi_sql_view.py
  bi_sql_editor/models/bi_sql_view.py
Labels: bot is merging ⏳

#760 Update CONFIGURE.rst
  report_qweb_signer/readme/CONFIGURE.rst
Labels: bot is merging ⏳

#639 [FIX] kpi_dashboard: Meter widget can show actual values
  kpi_dashboard/demo/demo_dashboard.xml
  kpi_dashboard/readme/CONFIGURE.rst
  kpi_dashboard/static/src/js/widget/meter_widget.js
Labels: approved, bot is merging ⏳

#773 [FIX] report_csv: Assign 'reportname' variable before accessing it
  report_csv/controllers/main.py
  report_csv/tests/test_report.py
Labels: approved, ready to merge, bot is merging ⏳

#769 [15.0][ADD] report_qweb_decimal_place
  report_qweb_decimal_place/README.rst
  report_qweb_decimal_place/__init__.py
  report_qweb_decimal_place/__manifest__.py
  report_qweb_decimal_place/models/__init__.py
  report_qweb_decimal_place/models/res_currency.py
  report_qweb_decimal_place/readme/CONFIGURE.rst
  report_qweb_decimal_place/readme/DESCRIPTION.rst
  report_qweb_decimal_place/reports/price_unit_value_format.xml
  report_qweb_decimal_place/static/description/index.html
  report_qweb_decimal_place/views/res_currency_views.xml
  setup/report_qweb_decimal_place/odoo/addons/report_qweb_decimal_place
  setup/report_qweb_decimal_place/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#709 [16.0][ADD] report_qweb_decimal_place
  report_qweb_decimal_place/README.rst
  report_qweb_decimal_place/__init__.py
  report_qweb_decimal_place/__manifest__.py
  report_qweb_decimal_place/models/__init__.py
  report_qweb_decimal_place/models/res_currency.py
  report_qweb_decimal_place/readme/CONFIGURE.rst
  report_qweb_decimal_place/readme/DESCRIPTION.rst
  report_qweb_decimal_place/reports/price_unit_value_format.xml
  report_qweb_decimal_place/static/description/index.html
  report_qweb_decimal_place/views/res_currency_views.xml
  setup/report_qweb_decimal_place/odoo/addons/report_qweb_decimal_place
  setup/report_qweb_decimal_place/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#774 [15.0][FIX] base_comment_template: Fix access error
  base_comment_template/models/base_comment_template.py
Labels: approved, bot is merging ⏳

#711 [13.0][IMP] report_csv: add encoding option
  report_csv/README.rst
  report_csv/__manifest__.py
  report_csv/models/ir_report.py
  report_csv/readme/CONFIGURE.rst
  report_csv/readme/CONTRIBUTORS.rst
  report_csv/readme/USAGE.rst
  report_csv/report/report_csv.py
  report_csv/static/description/index.html
  report_csv/tests/test_report.py
  report_csv/views/ir_actions_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#778 [15.0][FIX] base_comment_template: search when multiple models in a template
  base_comment_template/models/base_comment_template.py
  base_comment_template/models/comment_template.py
Labels: approved, bot is merging ⏳

#780 [16.0][FIX] base_comment_template: search when multiple models in a template
  base_comment_template/models/base_comment_template.py
  base_comment_template/models/comment_template.py
Labels: bot is merging ⏳
