Repository OCA/reporting-engine, pull requests merged in 2023-03, with the labels that each got.

#716 [16.0][IMP] report_xml: Added `xml_extension`
  report_xml/controllers/report.py
  report_xml/models/ir_actions_report.py
  report_xml/tests/test_report_xml.py
  report_xml/views/ir_actions_report_view.xml
Labels: bot is merging ⏳

#624 [15.0][MIG] report_async
  report_async/README.rst
  report_async/__init__.py
  report_async/__manifest__.py
  report_async/data/mail_template.xml
  report_async/data/queue_job_function_data.xml
  report_async/demo/report_async_demo.xml
  report_async/i18n/report_async.pot
  report_async/models/__init__.py
  report_async/models/ir_actions.py
  report_async/models/ir_report.py
  report_async/models/report_async.py
  report_async/readme/CONTRIBUTORS.rst
  report_async/readme/DESCRIPTION.rst
  report_async/readme/USAGE.rst
  report_async/security/ir.model.access.csv
  report_async/security/ir_rule.xml
  report_async/static/description/icon.png
  report_async/static/description/index.html
  report_async/tests/__init__.py
  report_async/tests/test_report_async.py
  report_async/views/report_async.xml
  report_async/wizard/__init__.py
  report_async/wizard/print_report_wizard.py
  report_async/wizard/print_report_wizard.xml
  setup/report_async/odoo/addons/report_async
  setup/report_async/setup.py
Labels: bot is merging ⏳

#736 [16.0] report_xlsx: fix exception handling
  report_xlsx/controllers/main.py
Labels: approved, bot is merging ⏳

#719 [ADD] module board_eval_context
  board_eval_context/README.rst
  board_eval_context/__init__.py
  board_eval_context/__manifest__.py
  board_eval_context/models/__init__.py
  board_eval_context/models/board_board.py
  board_eval_context/readme/DESCRIPTION.rst
  board_eval_context/static/description/index.html
  setup/board_eval_context/odoo/addons/board_eval_context
  setup/board_eval_context/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#708 [MIG][16.0] report label
  report_label/README.rst
  report_label/__init__.py
  report_label/__manifest__.py
  report_label/demo/demo.xml
  report_label/i18n/report_label.pot
  report_label/migrations/16.0.1.0.0/pre-migration.py
  report_label/models/__init__.py
  report_label/models/ir_actions_report.py
  report_label/models/ir_actions_server.py
  report_label/models/report_paperformat_label.py
  report_label/readme/CONFIGURE.rst
  report_label/readme/CONTRIBUTORS.rst
  report_label/readme/DESCRIPTION.rst
  report_label/readme/ROADMAP.rst
  report_label/readme/USAGE.rst
  report_label/reports/report_label.xml
  report_label/security/ir.model.access.csv
  report_label/static/description/icon.png
  report_label/static/description/index.html
  report_label/static/description/ir_actions_server_form.png
  report_label/static/description/report_label_wizard_form.png
  report_label/static/description/report_paperformat_label_form.png
  report_label/static/description/report_result.png
  report_label/tests/__init__.py
  report_label/tests/test_report_label.py
  report_label/views/ir_actions_server.xml
  report_label/views/report_paperformat_label.xml
  report_label/wizards/__init__.py
  report_label/wizards/report_label_wizard.py
  report_label/wizards/report_label_wizard.xml
  report_label/wizards/report_label_wizard_line.py
  setup/report_label/odoo/addons/report_label
  setup/report_label/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#681 [MIG] report_qweb_encrypt: Migration to 15.0
  report_qweb_encrypt/README.rst
  report_qweb_encrypt/__init__.py
  report_qweb_encrypt/__manifest__.py
  report_qweb_encrypt/controllers/__init__.py
  report_qweb_encrypt/controllers/main.py
  report_qweb_encrypt/i18n/es.po
  report_qweb_encrypt/i18n/report_qweb_encrypt.pot
  report_qweb_encrypt/models/__init__.py
  report_qweb_encrypt/models/ir_actions_report.py
  report_qweb_encrypt/readme/CONTRIBUTORS.rst
  report_qweb_encrypt/readme/DESCRIPTION.rst
  report_qweb_encrypt/readme/USAGE.rst
  report_qweb_encrypt/static/description/icon.png
  report_qweb_encrypt/static/description/index.html
  report_qweb_encrypt/static/src/js/report/action_manager_report.esm.js
  report_qweb_encrypt/static/src/js/report/encrypt_dialog.xml
  report_qweb_encrypt/tests/__init__.py
  report_qweb_encrypt/tests/test_report_qweb_encrypt.py
  report_qweb_encrypt/views/ir_actions_report.xml
  requirements.txt
  setup/report_qweb_encrypt/odoo/addons/report_qweb_encrypt
  setup/report_qweb_encrypt/setup.py
Labels: bot is merging ⏳

#703 [16.0][ADD] report_company_details_translatable
  report_company_details_translatable/README.rst
  report_company_details_translatable/__init__.py
  report_company_details_translatable/__manifest__.py
  report_company_details_translatable/models/__init__.py
  report_company_details_translatable/models/res_company.py
  report_company_details_translatable/readme/DESCRIPTION.rst
  report_company_details_translatable/static/description/index.html
  setup/report_company_details_translatable/odoo/addons/report_company_details_translatable
  setup/report_company_details_translatable/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#605 [15.0][MIG] report_csv: Migration to 15.0
  report_csv/README.rst
  report_csv/__init__.py
  report_csv/__manifest__.py
  report_csv/controllers/__init__.py
  report_csv/controllers/main.py
  report_csv/demo/report.xml
  report_csv/i18n/report_csv.pot
  report_csv/models/__init__.py
  report_csv/models/ir_report.py
  report_csv/readme/CONTRIBUTORS.rst
  report_csv/readme/DESCRIPTION.rst
  report_csv/readme/USAGE.rst
  report_csv/report/__init__.py
  report_csv/report/report_csv.py
  report_csv/report/report_partner_csv.py
  report_csv/static/description/icon.png
  report_csv/static/description/index.html
  report_csv/static/src/js/report/qwebactionmanager.esm.js
  report_csv/tests/__init__.py
  report_csv/tests/test_report.py
  setup/report_csv/odoo/addons/report_csv
  setup/report_csv/setup.py
Labels: approved, bot is merging ⏳

#540 [ADD] 'single-page' and 'multi-page' classes in report_qweb_element_p…
  report_qweb_element_page_visibility/views/layouts.xml
Labels: approved, ready to merge, bot is merging ⏳, no stale

#737 [ADD] page-count classes for element visibility
  report_qweb_element_page_visibility/views/layouts.xml
Labels: bot is merging ⏳

#713 [16.0][MIG] report_qweb_element_page_visibility: Migration to 16.0
  report_qweb_element_page_visibility/README.rst
  report_qweb_element_page_visibility/__init__.py
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/i18n/it.po
  report_qweb_element_page_visibility/i18n/report_qweb_element_page_visibility.pot
  report_qweb_element_page_visibility/readme/CONTRIBUTORS.rst
  report_qweb_element_page_visibility/readme/CREDITS.rst
  report_qweb_element_page_visibility/readme/DESCRIPTION.rst
  report_qweb_element_page_visibility/readme/USAGE.rst
  report_qweb_element_page_visibility/static/description/icon.png
  report_qweb_element_page_visibility/static/description/index.html
  report_qweb_element_page_visibility/views/layouts.xml
  setup/report_qweb_element_page_visibility/odoo/addons/report_qweb_element_page_visibility
  setup/report_qweb_element_page_visibility/setup.py
Labels: approved, ready to merge, bot is merging ⏳
