Repository OCA/reporting-engine, pull requests merged in 2023-04, with the labels that each got.

#734 [16.0][MIG] report_qweb_pdf_watermark: Migration to 16.0
  report_qweb_pdf_watermark/README.rst
  report_qweb_pdf_watermark/__init__.py
  report_qweb_pdf_watermark/__manifest__.py
  report_qweb_pdf_watermark/demo/report.xml
  report_qweb_pdf_watermark/i18n/ca.po
  report_qweb_pdf_watermark/i18n/da.po
  report_qweb_pdf_watermark/i18n/de.po
  report_qweb_pdf_watermark/i18n/el_GR.po
  report_qweb_pdf_watermark/i18n/es.po
  report_qweb_pdf_watermark/i18n/es_CO.po
  report_qweb_pdf_watermark/i18n/fr.po
  report_qweb_pdf_watermark/i18n/gl.po
  report_qweb_pdf_watermark/i18n/hr.po
  report_qweb_pdf_watermark/i18n/hr_HR.po
  report_qweb_pdf_watermark/i18n/it.po
  report_qweb_pdf_watermark/i18n/nb_NO.po
  report_qweb_pdf_watermark/i18n/nl_NL.po
  report_qweb_pdf_watermark/i18n/pl.po
  report_qweb_pdf_watermark/i18n/pt.po
  report_qweb_pdf_watermark/i18n/pt_BR.po
  report_qweb_pdf_watermark/i18n/pt_PT.po
  report_qweb_pdf_watermark/i18n/report_qweb_pdf_watermark.pot
  report_qweb_pdf_watermark/i18n/sl.po
  report_qweb_pdf_watermark/i18n/tr.po
  report_qweb_pdf_watermark/i18n/tr_TR.po
  report_qweb_pdf_watermark/models/__init__.py
  report_qweb_pdf_watermark/models/report.py
  report_qweb_pdf_watermark/models/res_company.py
  report_qweb_pdf_watermark/readme/CONTRIBUTORS.rst
  report_qweb_pdf_watermark/readme/DESCRIPTION.rst
  report_qweb_pdf_watermark/readme/HISTORY.rst
  report_qweb_pdf_watermark/readme/INSTALL.rst
  report_qweb_pdf_watermark/readme/ROADMAP.rst
  report_qweb_pdf_watermark/readme/USAGE.rst
  report_qweb_pdf_watermark/static/description/icon.png
  report_qweb_pdf_watermark/static/description/index.html
  report_qweb_pdf_watermark/static/src/css/report_qweb_pdf_watermark.css
  report_qweb_pdf_watermark/tests/__init__.py
  report_qweb_pdf_watermark/tests/test_report_qweb_pdf_watermark.py
  report_qweb_pdf_watermark/views/ir_actions_report_xml.xml
  report_qweb_pdf_watermark/views/res_company.xml
  setup/report_qweb_pdf_watermark/odoo/addons/report_qweb_pdf_watermark
  setup/report_qweb_pdf_watermark/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#751 [15.0][FIX] report_xlsx: make sure variable is known
  report_xlsx/controllers/main.py
Labels: approved, bot is merging ⏳

#752 [FIX][15.0] report_xlsx - IndexError
  report_xlsx/controllers/main.py
Labels: approved, bot is merging ⏳

#507 [IMP] - use display for element visibility
  report_qweb_element_page_visibility/views/layouts.xml
Labels: approved, ready to merge, bot is merging ⏳, no stale

#754 [13.0][FIX] base_comment_template: Consider multi-company and partners
  base_comment_template/models/comment_template.py
  base_comment_template/tests/test_base_comment_template.py
Labels: approved, bot is merging ⏳

#756 [14.0][FIX] base_comment_template: Consider multi-company and partners
  base_comment_template/models/comment_template.py
  base_comment_template/tests/test_base_comment_template.py
Labels: approved, bot is merging ⏳
