Repository OCA/reporting-engine, pull requests merged in 2023-12, with the labels that each got.

#819 [17.0][MIG] report_xlsx: Migration to 17.0
  report_xlsx/README.rst
  report_xlsx/__init__.py
  report_xlsx/__manifest__.py
  report_xlsx/controllers/__init__.py
  report_xlsx/controllers/main.py
  report_xlsx/demo/report.xml
  report_xlsx/i18n/ca.po
  report_xlsx/i18n/de.po
  report_xlsx/i18n/es.po
  report_xlsx/i18n/fr.po
  report_xlsx/i18n/hr.po
  report_xlsx/i18n/hr_HR.po
  report_xlsx/i18n/it.po
  report_xlsx/i18n/nl_NL.po
  report_xlsx/i18n/pt.po
  report_xlsx/i18n/pt_PT.po
  report_xlsx/i18n/report_xlsx.pot
  report_xlsx/i18n/sv.po
  report_xlsx/i18n/tr.po
  report_xlsx/models/__init__.py
  report_xlsx/models/ir_report.py
  report_xlsx/pyproject.toml
  report_xlsx/readme/CONTRIBUTORS.md
  report_xlsx/readme/DESCRIPTION.md
  report_xlsx/readme/INSTALL.md
  report_xlsx/readme/USAGE.md
  report_xlsx/report/__init__.py
  report_xlsx/report/report_abstract_xlsx.py
  report_xlsx/report/report_partner_xlsx.py
  report_xlsx/static/description/icon.png
  report_xlsx/static/description/index.html
  report_xlsx/static/src/js/report/action_manager_report.esm.js
  report_xlsx/tests/__init__.py
  report_xlsx/tests/test_report.py
  requirements.txt
Labels: bot is merging ⏳

#797 [FIX] report_substitute: support for email
  report_qweb_encrypt/models/ir_actions_report.py
  report_substitute/models/ir_actions_report.py
Labels: approved, ready to merge, bot is merging ⏳

#783 [16.0][MIG] report_context: Migration to 16.0
  report_context/README.rst
  report_context/__init__.py
  report_context/__manifest__.py
  report_context/controllers/__init__.py
  report_context/controllers/main.py
  report_context/data/config_parameter.xml
  report_context/i18n/report_context.pot
  report_context/models/__init__.py
  report_context/models/ir_actions_report.py
  report_context/readme/CONTRIBUTORS.rst
  report_context/readme/DESCRIPTION.rst
  report_context/readme/USAGE.rst
  report_context/static/description/icon.png
  report_context/static/description/index.html
  report_context/tests/__init__.py
  report_context/tests/test_report_context.py
  report_context/views/ir_actions_report.xml
  setup/report_context/odoo/addons/report_context
  setup/report_context/setup.py
Labels: approved, bot is merging ⏳

#816 [17.0][MIG] report_qweb_parameter: Migration to 17.0
  report_qweb_parameter/README.rst
  report_qweb_parameter/__init__.py
  report_qweb_parameter/__manifest__.py
  report_qweb_parameter/demo/test_report_field_length.xml
  report_qweb_parameter/i18n/ca.po
  report_qweb_parameter/i18n/es.po
  report_qweb_parameter/i18n/fr.po
  report_qweb_parameter/i18n/it.po
  report_qweb_parameter/i18n/pt.po
  report_qweb_parameter/i18n/report_qweb_parameter.pot
  report_qweb_parameter/models/__init__.py
  report_qweb_parameter/models/ir_qweb.py
  report_qweb_parameter/pyproject.toml
  report_qweb_parameter/readme/CONTRIBUTORS.md
  report_qweb_parameter/readme/DESCRIPTION.md
  report_qweb_parameter/readme/USAGE.md
  report_qweb_parameter/static/description/icon.png
  report_qweb_parameter/static/description/index.html
  report_qweb_parameter/tests/__init__.py
  report_qweb_parameter/tests/test_report_qweb_parameter.py
Labels: bot is merging ⏳

#825 16.0][FIX] report_label fix a security issue
  report_label/wizards/report_label_wizard.py
  report_label/wizards/report_label_wizard_line.py
Labels: approved, bot is merging ⏳

#823 [16.0][IMP] bi_sql_editor
  bi_sql_editor/demo/bi_sql_view_demo.xml
  bi_sql_editor/models/bi_sql_view.py
  bi_sql_editor/models/bi_sql_view_field.py
  bi_sql_editor/tests/test_bi_sql_view.py
  bi_sql_editor/views/view_bi_sql_view.xml
Labels: bot is merging ⏳

#784 [16.0][IMP] base_comment_template: allow to show code view in text field
  base_comment_template/views/base_comment_template_view.xml
Labels: approved, bot is merging ⏳, stale
