Repository OCA/reporting-engine, pull requests merged in 2023-10, with the labels that each got.

#767 [16.0][FIX] report_xlsx: Save as attachment
  report_xlsx/models/ir_report.py
  report_xlsx/readme/CONTRIBUTORS.rst
  report_xlsx/tests/test_report.py
Labels: approved, bot is merging ⏳, stale

#718 [16.0][IMP] Add back the variable feature in sql_export
  sql_export/__manifest__.py
  sql_export/demo/ir_model_fields.xml
  sql_export/demo/sql_export.xml
  sql_export/models/sql_export.py
  sql_export/readme/DESCRIPTION.rst
  sql_export/readme/ROADMAP.rst
  sql_export/readme/USAGE.rst
  sql_export/static/src/scss/modal_properties.scss
  sql_export/tests/test_sql_query.py
  sql_export/views/ir_model_fields_view.xml
  sql_export/views/sql_export_view.xml
  sql_export/wizard/wizard_file.py
  sql_export/wizard/wizard_file_view.xml
  sql_export_mail/models/sql_export.py
Labels: approved, bot is merging ⏳

#798 [13.0][ADD]report_xlsx_boilerplate
  report_xlsx/report/report_abstract_xlsx.py
  report_xlsx/tests/sample_files/test_partner_report_boilerplate_template.xlsx
  report_xlsx_boilerplate/__init__.py
  report_xlsx_boilerplate/__manifest__.py
  report_xlsx_boilerplate/readme/CONTRIBUTORS.rst
  report_xlsx_boilerplate/readme/DESCRIPTION.rst
  report_xlsx_boilerplate/readme/INSTALL.rst
  report_xlsx_boilerplate/readme/USAGE.rst
  report_xlsx_boilerplate/report/__init__.py
  report_xlsx_boilerplate/report/report_abstract_xlsx.py
  report_xlsx_boilerplate/report/utils/xlsx_utils.py
  report_xlsx_boilerplate/tests/__init__.py
  report_xlsx_boilerplate/tests/test_report.py
  requirements.txt
  setup/report_xlsx_boilerplate/odoo/addons/report_xlsx_boilerplate
  setup/report_xlsx_boilerplate/setup.py
Labels: approved, bot is merging ⏳

#804 [15.0][IMP] reporting-engine : test performance improvement
  report_xlsx/tests/test_report.py
  report_xlsx_helper/tests/test_report_xlsx_helper.py
  report_xml/tests/test_report_xml.py
Labels: bot is merging ⏳
