Repository OCA/reporting-engine, pull requests merged in 2023-11, with the labels that each got.

#741 [15.0][IMP] report_csv: add encoding option
  report_csv/README.rst
  report_csv/__manifest__.py
  report_csv/models/ir_report.py
  report_csv/readme/CONFIGURE.rst
  report_csv/readme/CONTRIBUTORS.rst
  report_csv/readme/USAGE.rst
  report_csv/report/report_csv.py
  report_csv/static/description/index.html
  report_csv/tests/test_report.py
  report_csv/views/ir_actions_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#742 [16.0][IMP] report_csv: add encoding option
  report_csv/README.rst
  report_csv/__manifest__.py
  report_csv/models/ir_report.py
  report_csv/readme/CONFIGURE.rst
  report_csv/readme/CONTRIBUTORS.rst
  report_csv/readme/USAGE.rst
  report_csv/report/report_csv.py
  report_csv/static/description/index.html
  report_csv/tests/test_report.py
  report_csv/views/ir_actions_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#801 [15.0][IMP] `bi_view_editor`: Restrict access to non BI View Editor Manager users
  bi_view_editor/__manifest__.py
  bi_view_editor/readme/USAGE.rst
  bi_view_editor/security/ir.model.access.csv
  bi_view_editor/security/res_groups.xml
  bi_view_editor/views/bve_view.xml
Labels: bot is merging ⏳

#805 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  base_comment_template/i18n/base_comment_template.pot
  base_comment_template/views/base_comment_template_view.xml
  base_comment_template/wizard/base_comment_template_preview_views.xml
  bi_sql_editor/models/bi_sql_view.py
  report_async/data/mail_template.xml
  report_async/i18n/report_async.pot
  report_async/views/report_async.xml
  report_context/data/config_parameter.xml
  report_label/data/paperformat_label.xml
  report_label/i18n/report_label.pot
  report_label/views/report_paperformat_label.xml
  report_layout_config/templates/report_templates.xml
  report_py3o/i18n/report_py3o.pot
  report_py3o/views/py3o_template.xml
  report_py3o_fusion_server/i18n/report_py3o_fusion_server.pot
  report_py3o_fusion_server/views/py3o_pdf_options.xml
  report_py3o_fusion_server/views/py3o_server.xml
  report_qweb_element_page_visibility/views/layouts.xml
  report_qweb_pdf_watermark/demo/report.xml
  report_qweb_signer/i18n/report_qweb_signer.pot
  report_qweb_signer/views/report_certificate_view.xml
Labels: help wanted, needs review, bot is merging ⏳

#807 [IMP] bi_view_editor: Restrict access to BI View Editor Managers
  bi_view_editor/__manifest__.py
  bi_view_editor/readme/USAGE.rst
  bi_view_editor/security/ir.model.access.csv
  bi_view_editor/security/res_groups.xml
  bi_view_editor/views/bve_view.xml
Labels: approved, bot is merging ⏳

#791 [16.0][FIX] report.py: docids = none
  report_xml/controllers/report.py
Labels: approved, bot is merging ⏳

#820 [16][FIX] sql_export : remove unused action parameter
  sql_export/models/sql_export.py
Labels: bot is merging ⏳

#800 [FIX] report_qweb_encrypt: Use _get_report instead of _get_report_from_name
  report_qweb_encrypt/models/ir_actions_report.py
Labels: bot is merging ⏳
