Repository OCA/reporting-engine, pull requests merged in 2024-11, with the labels that each got.

#946 [18.0][MIG] report_xlsx: Migration to 18.0.
  report_xlsx/README.rst
  report_xlsx/__init__.py
  report_xlsx/__manifest__.py
  report_xlsx/controllers/__init__.py
  report_xlsx/controllers/main.py
  report_xlsx/demo/report.xml
  report_xlsx/i18n/ca.po
  report_xlsx/i18n/de.po
  report_xlsx/i18n/es.po
  report_xlsx/i18n/fr.po
  report_xlsx/i18n/hr.po
  report_xlsx/i18n/hr_HR.po
  report_xlsx/i18n/it.po
  report_xlsx/i18n/nl_NL.po
  report_xlsx/i18n/pt.po
  report_xlsx/i18n/pt_PT.po
  report_xlsx/i18n/report_xlsx.pot
  report_xlsx/i18n/sv.po
  report_xlsx/i18n/tr.po
  report_xlsx/models/__init__.py
  report_xlsx/models/ir_report.py
  report_xlsx/pyproject.toml
  report_xlsx/readme/CONTRIBUTORS.md
  report_xlsx/readme/DESCRIPTION.md
  report_xlsx/readme/INSTALL.md
  report_xlsx/readme/USAGE.md
  report_xlsx/report/__init__.py
  report_xlsx/report/report_abstract_xlsx.py
  report_xlsx/report/report_partner_xlsx.py
  report_xlsx/static/description/icon.png
  report_xlsx/static/description/index.html
  report_xlsx/static/src/js/report/action_manager_report.esm.js
  report_xlsx/tests/__init__.py
  report_xlsx/tests/test_report.py
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#873 [16.0][ADD] sql_export_delta
  setup/sql_export_delta/odoo/addons/sql_export_delta
  setup/sql_export_delta/setup.py
  sql_export/models/sql_export.py
  sql_export/tests/test_sql_query.py
  sql_export/views/sql_export_view.xml
  sql_export/wizard/wizard_file.py
  sql_export_delta/README.rst
  sql_export_delta/__init__.py
  sql_export_delta/__manifest__.py
  sql_export_delta/hooks.py
  sql_export_delta/models/__init__.py
  sql_export_delta/models/sql_export.py
  sql_export_delta/readme/CONFIGURE.md
  sql_export_delta/readme/CONTRIBUTORS.md
  sql_export_delta/readme/DESCRIPTION.md
  sql_export_delta/static/description/icon.png
  sql_export_delta/static/description/index.html
  sql_export_delta/tests/__init__.py
  sql_export_delta/tests/test_sql_export_delta.py
  sql_export_delta/views/sql_export.xml
  sql_export_delta/wizards/__init__.py
  sql_export_delta/wizards/sql_file_wizard.py
Labels: approved, bot is merging ⏳, stale

#908 17.0 imp bi sql editor allow form view port 839
  bi_sql_editor/__manifest__.py
  bi_sql_editor/migrations/17.0.2.0.0/end-migration.py
  bi_sql_editor/models/bi_sql_view.py
  bi_sql_editor/models/bi_sql_view_field.py
  bi_sql_editor/static/description/index.html
  bi_sql_editor/views/view_bi_sql_view.xml
Labels: bot is merging ⏳, stale

#909 16.0 imp bi sql editor extra info display
  bi_sql_editor/views/view_bi_sql_view.xml
Labels: bot is merging ⏳, stale

#841 [17.0][MIG] report_qweb_pdf_watermark
  report_qweb_pdf_watermark/README.rst
  report_qweb_pdf_watermark/__init__.py
  report_qweb_pdf_watermark/__manifest__.py
  report_qweb_pdf_watermark/demo/report.xml
  report_qweb_pdf_watermark/i18n/ca.po
  report_qweb_pdf_watermark/i18n/da.po
  report_qweb_pdf_watermark/i18n/de.po
  report_qweb_pdf_watermark/i18n/el_GR.po
  report_qweb_pdf_watermark/i18n/es.po
  report_qweb_pdf_watermark/i18n/es_CO.po
  report_qweb_pdf_watermark/i18n/fr.po
  report_qweb_pdf_watermark/i18n/gl.po
  report_qweb_pdf_watermark/i18n/hr.po
  report_qweb_pdf_watermark/i18n/hr_HR.po
  report_qweb_pdf_watermark/i18n/it.po
  report_qweb_pdf_watermark/i18n/nb_NO.po
  report_qweb_pdf_watermark/i18n/nl_NL.po
  report_qweb_pdf_watermark/i18n/pl.po
  report_qweb_pdf_watermark/i18n/pt.po
  report_qweb_pdf_watermark/i18n/pt_BR.po
  report_qweb_pdf_watermark/i18n/pt_PT.po
  report_qweb_pdf_watermark/i18n/report_qweb_pdf_watermark.pot
  report_qweb_pdf_watermark/i18n/sl.po
  report_qweb_pdf_watermark/i18n/tr.po
  report_qweb_pdf_watermark/i18n/tr_TR.po
  report_qweb_pdf_watermark/models/__init__.py
  report_qweb_pdf_watermark/models/report.py
  report_qweb_pdf_watermark/models/res_company.py
  report_qweb_pdf_watermark/pyproject.toml
  report_qweb_pdf_watermark/readme/CONTRIBUTORS.md
  report_qweb_pdf_watermark/readme/DESCRIPTION.md
  report_qweb_pdf_watermark/readme/HISTORY.md
  report_qweb_pdf_watermark/readme/INSTALL.md
  report_qweb_pdf_watermark/readme/ROADMAP.md
  report_qweb_pdf_watermark/readme/USAGE.md
  report_qweb_pdf_watermark/static/description/icon.png
  report_qweb_pdf_watermark/static/description/index.html
  report_qweb_pdf_watermark/static/src/css/report_qweb_pdf_watermark.css
  report_qweb_pdf_watermark/tests/__init__.py
  report_qweb_pdf_watermark/tests/test_report_qweb_pdf_watermark.py
  report_qweb_pdf_watermark/views/ir_actions_report_xml.xml
  report_qweb_pdf_watermark/views/res_company.xml
Labels: approved, bot is merging ⏳

#950 [IMP] Add _get_pdf_watermark function to be able to inherit and select a pdf from another model.
  report_qweb_pdf_watermark/README.rst
  report_qweb_pdf_watermark/models/report.py
  report_qweb_pdf_watermark/readme/CONTRIBUTORS.rst
  report_qweb_pdf_watermark/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳
