Repository OCA/reporting-engine, pull requests merged in 2024-05, with the labels that each got.

#874 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  bi_sql_editor/models/bi_sql_view.py
  report_xlsx_helper/report/report_xlsx_abstract.py
Labels: help wanted, needs review, bot is merging ⏳

#785 [16.0][IMP] base_comment_template: update readme files
  base_comment_template/README.rst
  base_comment_template/readme/DESCRIPTION.rst
  base_comment_template/readme/USAGE.rst
  base_comment_template/static/description/index.html
Labels: bot is merging ⏳

#814 [15.0][MIG] kpi_dashboard
  kpi_dashboard/README.rst
  kpi_dashboard/__init__.py
  kpi_dashboard/__manifest__.py
  kpi_dashboard/demo/demo_dashboard.xml
  kpi_dashboard/i18n/kpi_dashboard.pot
  kpi_dashboard/models/__init__.py
  kpi_dashboard/models/ir_actions_act_window_view.py
  kpi_dashboard/models/ir_ui_view.py
  kpi_dashboard/models/kpi_dashboard.py
  kpi_dashboard/models/kpi_kpi.py
  kpi_dashboard/readme/CONFIGURE.rst
  kpi_dashboard/readme/CONTRIBUTORS.rst
  kpi_dashboard/readme/DESCRIPTION.rst
  kpi_dashboard/security/ir.model.access.csv
  kpi_dashboard/security/security.xml
  kpi_dashboard/static/description/icon.png
  kpi_dashboard/static/description/index.html
  kpi_dashboard/static/lib/gauge/GaugeMeter.js
  kpi_dashboard/static/lib/gridster/jquery.dsmorse-gridster.min.css
  kpi_dashboard/static/lib/gridster/jquery.dsmorse-gridster.min.js
  kpi_dashboard/static/lib/nvd3/d3.v3.js
  kpi_dashboard/static/lib/nvd3/nv.d3.css
  kpi_dashboard/static/lib/nvd3/nv.d3.js
  kpi_dashboard/static/src/js/dashboard_controller.js
  kpi_dashboard/static/src/js/dashboard_model.js
  kpi_dashboard/static/src/js/dashboard_renderer.js
  kpi_dashboard/static/src/js/dashboard_view.js
  kpi_dashboard/static/src/js/field_widget.js
  kpi_dashboard/static/src/js/lib/nvd3.js
  kpi_dashboard/static/src/js/widget/abstract_widget.js
  kpi_dashboard/static/src/js/widget/counter_widget.js
  kpi_dashboard/static/src/js/widget/graph_widget.js
  kpi_dashboard/static/src/js/widget/integer_widget.js
  kpi_dashboard/static/src/js/widget/meter_widget.js
  kpi_dashboard/static/src/js/widget/number_widget.js
  kpi_dashboard/static/src/js/widget/text_widget.js
  kpi_dashboard/static/src/js/widget_registry.js
  kpi_dashboard/static/src/scss/kpi_dashboard.scss
  kpi_dashboard/static/src/xml/dashboard.xml
  kpi_dashboard/tests/__init__.py
  kpi_dashboard/tests/test_formula.py
  kpi_dashboard/tests/test_kpi_dashboard.py
  kpi_dashboard/views/kpi_dashboard.xml
  kpi_dashboard/views/kpi_kpi.xml
  kpi_dashboard/views/kpi_menu.xml
  kpi_dashboard/wizards/__init__.py
  kpi_dashboard/wizards/kpi_dashboard_menu.py
  kpi_dashboard/wizards/kpi_dashboard_menu.xml
  setup/kpi_dashboard/odoo/addons/kpi_dashboard
  setup/kpi_dashboard/setup.py
Labels: needs review, approved, bot is merging ⏳

#853 [16.0][FIX] report_async: replaced parent menu
  report_async/__manifest__.py
  report_async/views/report_async.xml
Labels: approved, bot is merging ⏳
