Repository OCA/reporting-engine, pull requests merged in 2024-07, with the labels that each got.

#904 [12.0][IMP] report_async: add schedule_date field
  report_async/models/report_async.py
  report_async/views/report_async.xml
Labels: approved, ready to merge, bot is merging ⏳

#793 [16.0][IMP] report_csv: support attachment use
  report_csv/models/ir_report.py
  report_csv/tests/test_report.py
Labels: bot is merging ⏳

#902 [16.0][FIX] base_comment_template: script pre-migration
  base_comment_template/migrations/16.0.1.1.0/pre-migration.py
Labels: approved, bot is merging ⏳

#839 [IMP] bi_sql_editor: allow to generate form view + use sum / avg on tree view
  bi_sql_editor/__manifest__.py
  bi_sql_editor/migrations/16.0.2.0.0/end-migration.py
  bi_sql_editor/models/bi_sql_view.py
  bi_sql_editor/models/bi_sql_view_field.py
  bi_sql_editor/static/description/index.html
  bi_sql_editor/views/view_bi_sql_view.xml
Labels: bot is merging ⏳

#910 [16.0] FIX] report_py3o: fix error in py3o_context_parser
  report_py3o/models/_py3o_parser_context.py
Labels: approved, bot is merging ⏳

#912 [16.0][FIX] report_substitute: adding change of main method
  report_substitute/wizards/mail_compose_message.py
Labels: bot is merging ⏳
