Repository OCA/reporting-engine, pull requests merged in 2024-01, with the labels that each got.

#833 [IMP][16.0]base_comment_template: using markup.safe to render html in report
  base_comment_template/models/comment_template.py
Labels: approved, ready to merge, bot is merging ⏳

#831 [17.0][MIG] report xlsx helper: Migration to 17.0
  report_xlsx_helper/README.rst
  report_xlsx_helper/__init__.py
  report_xlsx_helper/__manifest__.py
  report_xlsx_helper/controllers/__init__.py
  report_xlsx_helper/controllers/main.py
  report_xlsx_helper/i18n/ca.po
  report_xlsx_helper/i18n/es.po
  report_xlsx_helper/i18n/report_xlsx_helper.pot
  report_xlsx_helper/models/__init__.py
  report_xlsx_helper/models/ir_actions_report.py
  report_xlsx_helper/pyproject.toml
  report_xlsx_helper/readme/CONTRIBUTORS.md
  report_xlsx_helper/readme/DESCRIPTION.md
  report_xlsx_helper/readme/INSTALL.md
  report_xlsx_helper/readme/USAGE.md
  report_xlsx_helper/report/__init__.py
  report_xlsx_helper/report/report_xlsx_abstract.py
  report_xlsx_helper/report/report_xlsx_format.py
  report_xlsx_helper/report/test_partner_report_xlsx.py
  report_xlsx_helper/static/description/icon.png
  report_xlsx_helper/static/description/index.html
  report_xlsx_helper/tests/__init__.py
  report_xlsx_helper/tests/test_report_xlsx_helper.py
Labels: approved, ready to merge, bot is merging ⏳

#848 [15.0][IMP] bi_sql_editor: create filters for date fields.
  bi_sql_editor/models/bi_sql_view_field.py
Labels: approved, bot is merging ⏳

#850 [16.0][IMP] bi_sql_editor: create filters for date fields.
  bi_sql_editor/models/bi_sql_view_field.py
Labels: bot is merging ⏳
