Repository OCA/reporting-engine, pull requests merged in 2024-08, with the labels that each got.

#914 [15.0][FIX] base_comment_template: check table `base_comment_template_ir_model_rel` exits before update it
  base_comment_template/migrations/15.0.1.1.0/pre-migration.py
Labels: approved, bot is merging ⏳

#840 [17.0][MIG] report_qweb_element_page_visibility
  report_qweb_element_page_visibility/README.rst
  report_qweb_element_page_visibility/__init__.py
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/i18n/it.po
  report_qweb_element_page_visibility/i18n/report_qweb_element_page_visibility.pot
  report_qweb_element_page_visibility/pyproject.toml
  report_qweb_element_page_visibility/readme/CONTRIBUTORS.md
  report_qweb_element_page_visibility/readme/CREDITS.md
  report_qweb_element_page_visibility/readme/DESCRIPTION.md
  report_qweb_element_page_visibility/readme/USAGE.md
  report_qweb_element_page_visibility/static/description/icon.png
  report_qweb_element_page_visibility/static/description/index.html
  report_qweb_element_page_visibility/views/layouts.xml
Labels: approved, bot is merging ⏳

#869 [14.0][DOC] report_xlsx: Update USAGE.rst
  report_xlsx/readme/USAGE.rst
Labels: bot is merging ⏳, stale

#919 [17.0][FW][DOC] report_xlsx: Update USAGE.rst
  report_xlsx/readme/USAGE.md
Labels: bot is merging ⏳
