Repository OCA/reporting-engine, pull requests merged in 2024-06, with the labels that each got.

#891 [13.0][IMP]bi_sql_editor: add parent menu as an editable parameter when creating UI elements
  bi_sql_editor/models/bi_sql_view.py
  bi_sql_editor/readme/CONFIGURE.rst
  bi_sql_editor/readme/CONTRIBUTORS.rst
  bi_sql_editor/views/view_bi_sql_view.xml
Labels: approved, bot is merging ⏳

#887 [FIX] bi_sql_editor : prevent to raise an error when creating a cron for a materialized view,
  bi_sql_editor/models/bi_sql_view.py
Labels: approved, ready to merge, bot is merging ⏳

#884 [16.0][ADD] report_text_format_option
  report_text_format_option/README.rst
  report_text_format_option/__init__.py
  report_text_format_option/__manifest__.py
  report_text_format_option/demo/report_demo.xml
  report_text_format_option/models/__init__.py
  report_text_format_option/models/ir_actions_report.py
  report_text_format_option/readme/CONFIGURE.rst
  report_text_format_option/readme/DESCRIPTION.rst
  report_text_format_option/static/description/index.html
  report_text_format_option/tests/__init__.py
  report_text_format_option/tests/test_report_format_option.py
  report_text_format_option/views/ir_actions_report_views.xml
  setup/report_text_format_option/odoo/addons/report_text_format_option
  setup/report_text_format_option/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#893 [14.0][FW][IMP]bi_sql_editor: add parent menu as an editable parameter when creating UI elements
  bi_sql_editor/models/bi_sql_view.py
  bi_sql_editor/readme/CONFIGURE.rst
  bi_sql_editor/readme/CONTRIBUTORS.rst
  bi_sql_editor/views/view_bi_sql_view.xml
Labels: bot is merging ⏳

#896 [17.0][FW][IMP]bi_sql_editor: add parent menu as an editable parameter when creating UI elements
  bi_sql_editor/README.rst
  bi_sql_editor/models/bi_sql_view.py
  bi_sql_editor/readme/CONFIGURE.md
  bi_sql_editor/readme/CONTRIBUTORS.md
  bi_sql_editor/static/description/index.html
  bi_sql_editor/views/view_bi_sql_view.xml
Labels: bot is merging ⏳

#894 [15.0][FW][IMP]bi_sql_editor: add parent menu as an editable parameter when creating UI elements
  bi_sql_editor/models/bi_sql_view.py
  bi_sql_editor/readme/CONFIGURE.rst
  bi_sql_editor/readme/CONTRIBUTORS.rst
  bi_sql_editor/views/view_bi_sql_view.xml
Labels: bot is merging ⏳

#895 [16.0][FW][IMP]bi_sql_editor: add parent menu as an editable parameter when creating UI elements
  bi_sql_editor/models/bi_sql_view.py
  bi_sql_editor/readme/CONFIGURE.rst
  bi_sql_editor/readme/CONTRIBUTORS.rst
  bi_sql_editor/views/view_bi_sql_view.xml
Labels: bot is merging ⏳

#897 [ADD] [16.0] report_display_name_in_footer
  report_display_name_in_footer/README.rst
  report_display_name_in_footer/__init__.py
  report_display_name_in_footer/__manifest__.py
  report_display_name_in_footer/data/report_data.xml
  report_display_name_in_footer/models/__init__.py
  report_display_name_in_footer/models/ir_actions_report.py
  report_display_name_in_footer/readme/CONFIGURE.md
  report_display_name_in_footer/readme/CONTEXT.md
  report_display_name_in_footer/readme/CONTRIBUTORS.md
  report_display_name_in_footer/readme/DESCRIPTION.md
  report_display_name_in_footer/readme/USAGE.md
  report_display_name_in_footer/static/description/icon.png
  report_display_name_in_footer/static/description/index.html
  report_display_name_in_footer/views/report_templates.xml
  setup/report_display_name_in_footer/odoo/addons/report_display_name_in_footer
  setup/report_display_name_in_footer/setup.py
Labels: approved, bot is merging ⏳

#900 [16][FIX] sql_export_mail : avoid trying to send mail for a not valid query
  sql_export_mail/models/sql_export.py
Labels: bot is merging ⏳

#880 [16] sql_export : Add last_run datetime field
  sql_export/models/sql_export.py
  sql_export/views/sql_export_view.xml
  sql_export/wizard/wizard_file.py
Labels: approved, bot is merging ⏳

#883 [17.0][MIG] report_layout_config: Migration to 17.0
  report_layout_config/README.rst
  report_layout_config/__init__.py
  report_layout_config/__manifest__.py
  report_layout_config/data/report_layout.xml
  report_layout_config/i18n/es.po
  report_layout_config/i18n/report_layout_config.pot
  report_layout_config/models/__init__.py
  report_layout_config/models/base_document_layout.py
  report_layout_config/models/res_company.py
  report_layout_config/pyproject.toml
  report_layout_config/readme/CONTRIBUTORS.md
  report_layout_config/readme/DESCRIPTION.md
  report_layout_config/readme/USAGE.md
  report_layout_config/static/description/icon.png
  report_layout_config/static/description/index.html
  report_layout_config/static/img/preview_standard.png
  report_layout_config/static/pdf/preview_standard.pdf
  report_layout_config/static/src/scss/style.scss
  report_layout_config/templates/report_templates.xml
  report_layout_config/views/document_layout.xml
Labels: approved, ready to merge, bot is merging ⏳

#901 [FIX] [16.0] report_display_name_in_footer: Param with noupdate
  report_display_name_in_footer/README.rst
  report_display_name_in_footer/data/report_data.xml
  report_display_name_in_footer/readme/ROADMAP.md
  report_display_name_in_footer/static/description/index.html
Labels: approved, bot is merging ⏳
