Repository OCA/reporting-engine, pull requests merged in 2025-08, with the labels that each got.

#1052 [18.0][FIX] bi_sql_editor: replaces deprecated group_operator by aggregator
  bi_sql_editor/__manifest__.py
  bi_sql_editor/models/bi_sql_view.py
Labels: bot is merging ⏳

#969 [17.0][MIG] bi_view_editor_spreadsheet_dashboard
  bi_view_editor_spreadsheet_dashboard/README.rst
  bi_view_editor_spreadsheet_dashboard/__init__.py
  bi_view_editor_spreadsheet_dashboard/__manifest__.py
  bi_view_editor_spreadsheet_dashboard/i18n/bi_view_editor_spreadsheet_dashboard.pot
  bi_view_editor_spreadsheet_dashboard/i18n/it.po
  bi_view_editor_spreadsheet_dashboard/pyproject.toml
  bi_view_editor_spreadsheet_dashboard/readme/CONTRIBUTORS.md
  bi_view_editor_spreadsheet_dashboard/readme/DESCRIPTION.md
  bi_view_editor_spreadsheet_dashboard/static/description/icon.png
  bi_view_editor_spreadsheet_dashboard/static/description/index.html
  bi_view_editor_spreadsheet_dashboard/views/menus.xml
Labels: approved, ready to merge, bot is merging ⏳

#1058 [16.0][FIX] Greenify CI
  report_qweb_signer/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#1040 [16.0][ADD] report_paperformat_company_dependent
  report_paperformat_company_dependent/README.rst
  report_paperformat_company_dependent/__init__.py
  report_paperformat_company_dependent/__manifest__.py
  report_paperformat_company_dependent/hooks.py
  report_paperformat_company_dependent/models/__init__.py
  report_paperformat_company_dependent/models/ir_actions_report.py
  report_paperformat_company_dependent/readme/CONTEXT.rst
  report_paperformat_company_dependent/readme/CONTRIBUTORS.rst
  report_paperformat_company_dependent/readme/DESCRIPTION.rst
  report_paperformat_company_dependent/static/description/index.html
  setup/report_paperformat_company_dependent/odoo/addons/report_paperformat_company_dependent
  setup/report_paperformat_company_dependent/setup.py
Labels: approved, bot is merging ⏳
