Repository OCA/reporting-engine, pull requests merged in 2025-05, with the labels that each got.

#952 [17.0][IMP] report_qweb_pdf_watermark: support pypdf >= 2.0
  report_qweb_pdf_watermark/README.rst
  report_qweb_pdf_watermark/__manifest__.py
  report_qweb_pdf_watermark/models/report.py
  report_qweb_pdf_watermark/static/description/index.html
Labels: approved, bot is merging ⏳, stale

#1007 [17.0][FIX] report_qweb_pdf_watermark: Recursive call in report rendering
  report_qweb_pdf_watermark/README.rst
  report_qweb_pdf_watermark/models/report.py
  report_qweb_pdf_watermark/readme/CONTRIBUTORS.md
  report_qweb_pdf_watermark/static/description/index.html
Labels: approved, bot is merging ⏳

#1017 [16.0][FIX] The field cron_id should be copy=False
  bi_sql_editor/models/bi_sql_view.py
Labels: bot is merging ⏳

#1018 [18.0][FIX] The field cron_id should be copy=False
  bi_sql_editor/models/bi_sql_view.py
Labels: bot is merging ⏳

#1020 [18.0][FIX] bi_sql_editor: Replace deprecated `datetime.utcnow()`
  bi_sql_editor/models/bi_sql_view.py
Labels: approved, bot is merging ⏳
