Repository OCA/reporting-engine, pull requests merged in 2025-01, with the labels that each got.

#845 [17.0][MIG] sql_export_mail
  sql_export_mail/README.rst
  sql_export_mail/__init__.py
  sql_export_mail/__manifest__.py
  sql_export_mail/data/mail_template.xml
  sql_export_mail/i18n/ca.po
  sql_export_mail/i18n/fr.po
  sql_export_mail/i18n/it.po
  sql_export_mail/i18n/sql_export_mail.pot
  sql_export_mail/models/__init__.py
  sql_export_mail/models/sql_export.py
  sql_export_mail/pyproject.toml
  sql_export_mail/readme/CONFIGURE.md
  sql_export_mail/readme/CONTRIBUTORS.md
  sql_export_mail/readme/DESCRIPTION.md
  sql_export_mail/static/description/icon.png
  sql_export_mail/static/description/index.html
  sql_export_mail/tests/__init__.py
  sql_export_mail/tests/test_sql_query_mail.py
  sql_export_mail/views/sql_export_view.xml
Labels: approved, bot is merging ⏳, stale

#815 [14.0][IMP] report_csv: add encoding option
  report_csv/README.rst
  report_csv/__manifest__.py
  report_csv/models/ir_report.py
  report_csv/readme/CONFIGURE.rst
  report_csv/readme/CONTRIBUTORS.rst
  report_csv/readme/USAGE.rst
  report_csv/report/report_csv.py
  report_csv/static/description/index.html
  report_csv/tests/test_report.py
  report_csv/views/ir_actions_views.xml
Labels: bot is merging ⏳

#963 [16.0][FIX] report_qweb_parameter: out and raw doesn't work with conditionals
  report_qweb_parameter/README.rst
  report_qweb_parameter/demo/test_report_field_length.xml
  report_qweb_parameter/models/ir_qweb.py
  report_qweb_parameter/readme/CONTRIBUTORS.rst
  report_qweb_parameter/static/description/index.html
  report_qweb_parameter/tests/test_report_qweb_parameter.py
Labels: approved, bot is merging ⏳

#964 [17.0][FIX] report_qweb_parameter: out and raw doesn't work with conditionals
  report_qweb_parameter/README.rst
  report_qweb_parameter/demo/test_report_field_length.xml
  report_qweb_parameter/models/ir_qweb.py
  report_qweb_parameter/readme/CONTRIBUTORS.md
  report_qweb_parameter/static/description/index.html
  report_qweb_parameter/tests/test_report_qweb_parameter.py
Labels: bot is merging ⏳
