Repository OCA/reporting-engine, pull requests merged in 2025-03, with the labels that each got.

#980 [17.0][MIG] report_csv: Migration to 17.0
  report_csv/README.rst
  report_csv/__init__.py
  report_csv/__manifest__.py
  report_csv/controllers/__init__.py
  report_csv/controllers/main.py
  report_csv/demo/report.xml
  report_csv/i18n/es.po
  report_csv/i18n/it.po
  report_csv/i18n/report_csv.pot
  report_csv/models/__init__.py
  report_csv/models/ir_report.py
  report_csv/pyproject.toml
  report_csv/readme/CONFIGURE.md
  report_csv/readme/CONTRIBUTORS.md
  report_csv/readme/DESCRIPTION.md
  report_csv/readme/USAGE.md
  report_csv/report/__init__.py
  report_csv/report/report_csv.py
  report_csv/report/report_partner_csv.py
  report_csv/static/description/icon.png
  report_csv/static/description/index.html
  report_csv/static/src/js/report/qwebactionmanager.esm.js
  report_csv/tests/__init__.py
  report_csv/tests/test_report.py
  report_csv/views/ir_actions_views.xml
Labels: bot is merging ⏳

#986 [16.0][IMP] report_py3o: refresh
  report_py3o/tests/test_report_py3o.py
Labels: bot is merging ⏳

#956 [18.0][MIG] report_qweb_element_page_visibility: Migration to 18.0
  report_qweb_element_page_visibility/README.rst
  report_qweb_element_page_visibility/__init__.py
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/i18n/it.po
  report_qweb_element_page_visibility/i18n/report_qweb_element_page_visibility.pot
  report_qweb_element_page_visibility/pyproject.toml
  report_qweb_element_page_visibility/readme/CONTRIBUTORS.md
  report_qweb_element_page_visibility/readme/CREDITS.md
  report_qweb_element_page_visibility/readme/DESCRIPTION.md
  report_qweb_element_page_visibility/readme/USAGE.md
  report_qweb_element_page_visibility/static/description/icon.png
  report_qweb_element_page_visibility/static/description/index.html
  report_qweb_element_page_visibility/views/layouts.xml
Labels: approved, ready to merge, bot is merging ⏳

#988 [16.0][REF] report_qweb_signer: make signing functions reusable
  report_qweb_signer/models/ir_actions_report.py
Labels: approved, bot is merging ⏳

#857 [16.0][ADD] report_qweb_field_option
  report_qweb_field_option/README.rst
  report_qweb_field_option/__init__.py
  report_qweb_field_option/__manifest__.py
  report_qweb_field_option/models/__init__.py
  report_qweb_field_option/models/ir_qweb.py
  report_qweb_field_option/models/qweb_field_options.py
  report_qweb_field_option/readme/CONFIGURE.rst
  report_qweb_field_option/readme/CONTRIBUTORS.rst
  report_qweb_field_option/readme/DESCRIPTION.rst
  report_qweb_field_option/readme/ROADMAP.rst
  report_qweb_field_option/readme/USAGE.rst
  report_qweb_field_option/security/ir.model.access.csv
  report_qweb_field_option/security/qweb_field_options_security.xml
  report_qweb_field_option/static/description/index.html
  report_qweb_field_option/tests/__init__.py
  report_qweb_field_option/tests/test_models.py
  report_qweb_field_option/tests/test_report_qweb_field_options.py
  report_qweb_field_option/views/qweb_field_options_views.xml
  requirements.txt
  setup/report_qweb_field_option/odoo/addons/report_qweb_field_option
  setup/report_qweb_field_option/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#992 [16.0][IMP] report_qweb_field_option: remove odoo_test_helper from manifest
  report_qweb_field_option/__manifest__.py
  report_qweb_field_option/static/description/index.html
  requirements.txt
  test-requirements.txt
Labels: approved, bot is merging ⏳

#990 [18.0][MIG] sql_export_excel
  requirements.txt
  sql_export_excel/README.rst
  sql_export_excel/__init__.py
  sql_export_excel/__manifest__.py
  sql_export_excel/i18n/ca.po
  sql_export_excel/i18n/es.po
  sql_export_excel/i18n/it.po
  sql_export_excel/i18n/sql_export_excel.pot
  sql_export_excel/models/__init__.py
  sql_export_excel/models/sql_export.py
  sql_export_excel/pyproject.toml
  sql_export_excel/readme/CONFIGURE.md
  sql_export_excel/readme/CONTRIBUTORS.md
  sql_export_excel/readme/DESCRIPTION.md
  sql_export_excel/static/description/icon.png
  sql_export_excel/static/description/index.html
  sql_export_excel/tests/__init__.py
  sql_export_excel/tests/test_sql_query_excel.py
  sql_export_excel/views/sql_export_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#996 [14.0] [FIX] report_label: avoid TypeError when viewing qweb templates from action.server form
  report_label/models/ir_actions_server.py
Labels: approved, bot is merging ⏳

#983 17.0 mig sql export excel
  requirements.txt
  sql_export_excel/README.rst
  sql_export_excel/__init__.py
  sql_export_excel/__manifest__.py
  sql_export_excel/i18n/ca.po
  sql_export_excel/i18n/es.po
  sql_export_excel/i18n/it.po
  sql_export_excel/i18n/sql_export_excel.pot
  sql_export_excel/models/__init__.py
  sql_export_excel/models/sql_export.py
  sql_export_excel/pyproject.toml
  sql_export_excel/readme/CONFIGURE.md
  sql_export_excel/readme/CONTRIBUTORS.md
  sql_export_excel/readme/DESCRIPTION.md
  sql_export_excel/static/description/icon.png
  sql_export_excel/static/description/index.html
  sql_export_excel/tests/__init__.py
  sql_export_excel/tests/test_sql_query_excel.py
  sql_export_excel/views/sql_export_view.xml
Labels: approved, bot is merging ⏳

#994 [FIX] report_substitute: avoid write over the mail template
  report_substitute/models/mail_thread.py
  report_substitute/wizards/mail_compose_message.py
Labels: approved, bot is merging ⏳
