Repository OCA/reporting-engine, pull requests merged in 2025-09, with the labels that each got.

#1055 [17.0][MIG] report_qweb_field_option: Migration to 17.0
  report_qweb_field_option/README.rst
  report_qweb_field_option/__init__.py
  report_qweb_field_option/__manifest__.py
  report_qweb_field_option/i18n/it.po
  report_qweb_field_option/i18n/report_qweb_field_option.pot
  report_qweb_field_option/models/__init__.py
  report_qweb_field_option/models/ir_qweb.py
  report_qweb_field_option/models/qweb_field_options.py
  report_qweb_field_option/pyproject.toml
  report_qweb_field_option/readme/CONFIGURE.md
  report_qweb_field_option/readme/CONTRIBUTORS.md
  report_qweb_field_option/readme/DESCRIPTION.md
  report_qweb_field_option/readme/ROADMAP.md
  report_qweb_field_option/readme/USAGE.md
  report_qweb_field_option/security/ir.model.access.csv
  report_qweb_field_option/security/qweb_field_options_security.xml
  report_qweb_field_option/static/description/icon.png
  report_qweb_field_option/static/description/index.html
  report_qweb_field_option/tests/__init__.py
  report_qweb_field_option/tests/test_models.py
  report_qweb_field_option/tests/test_report_qweb_field_options.py
  report_qweb_field_option/views/qweb_field_options_views.xml
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#1054 [16.0][IMP] report_qweb_field_option: update ROADMAP
  report_qweb_field_option/README.rst
  report_qweb_field_option/readme/CONFIGURE.rst
  report_qweb_field_option/readme/ROADMAP.rst
Labels: approved, ready to merge, bot is merging ⏳

#1065 [17.0][MIG] report_text_format_option
  report_text_format_option/README.rst
  report_text_format_option/__init__.py
  report_text_format_option/__manifest__.py
  report_text_format_option/demo/report_demo.xml
  report_text_format_option/i18n/it.po
  report_text_format_option/i18n/report_text_format_option.pot
  report_text_format_option/models/__init__.py
  report_text_format_option/models/ir_actions_report.py
  report_text_format_option/pyproject.toml
  report_text_format_option/readme/CONFIGURE.md
  report_text_format_option/readme/DESCRIPTION.md
  report_text_format_option/static/description/icon.png
  report_text_format_option/static/description/index.html
  report_text_format_option/tests/__init__.py
  report_text_format_option/tests/test_report_format_option.py
  report_text_format_option/views/ir_actions_report_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1047 [IMP] kpi: Add chatter to kpi
  kpi/models/kpi.py
  kpi/views/kpi_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1023 [18.0][IMP] report_qweb_pdf_watermark: support pypdf >= 2.0
  report_qweb_pdf_watermark/README.rst
  report_qweb_pdf_watermark/__manifest__.py
  report_qweb_pdf_watermark/models/report.py
  report_qweb_pdf_watermark/static/description/index.html
Labels: approved, bot is merging ⏳
