Repository OCA/reporting-engine, pull requests merged in 2025-06, with the labels that each got.

#939 [18.0][MIG] report_qweb_parameter: Migration to 18.0
  report_qweb_parameter/README.rst
  report_qweb_parameter/__init__.py
  report_qweb_parameter/__manifest__.py
  report_qweb_parameter/demo/test_report_field_length.xml
  report_qweb_parameter/i18n/ca.po
  report_qweb_parameter/i18n/es.po
  report_qweb_parameter/i18n/fr.po
  report_qweb_parameter/i18n/it.po
  report_qweb_parameter/i18n/pt.po
  report_qweb_parameter/i18n/report_qweb_parameter.pot
  report_qweb_parameter/models/__init__.py
  report_qweb_parameter/models/ir_qweb.py
  report_qweb_parameter/pyproject.toml
  report_qweb_parameter/readme/CONTRIBUTORS.md
  report_qweb_parameter/readme/DESCRIPTION.md
  report_qweb_parameter/readme/USAGE.md
  report_qweb_parameter/static/description/icon.png
  report_qweb_parameter/static/description/index.html
  report_qweb_parameter/tests/__init__.py
  report_qweb_parameter/tests/test_report_qweb_parameter.py
Labels: approved, ready to merge, bot is merging ⏳

#1027 [17.0][IMP] report_qweb_signer: Add incompatibility with `account_edi_ubl_c…
  report_qweb_signer/README.rst
  report_qweb_signer/readme/ROADMAP.md
  report_qweb_signer/static/description/index.html
Labels: approved, bot is merging ⏳

#927 [FIX] report_substitute: handle reports without xml_id
  report_substitute/models/ir_actions_report.py
Labels: approved, bot is merging ⏳, stale

#933 [17.0][FIX] report_xlsx: Preserve custom context by using context from report instead of user context
  report_xlsx/static/src/js/report/action_manager_report.esm.js
Labels: approved, bot is merging ⏳

#975 [16.0][FIX] report_async: fix mail template
  report_async/data/mail_template.xml
Labels: approved, bot is merging ⏳

#979 [IMP] sql_export_mail, add partner as export email recipient
  sql_export_mail/models/sql_export.py
  sql_export_mail/static/description/index.html
  sql_export_mail/tests/test_sql_query_mail.py
  sql_export_mail/views/sql_export_view.xml
Labels: approved, bot is merging ⏳

#1031 [18.0][MIG] pdf_helper renamed to pdf_xml_attachment
  pdf_xml_attachment/README.rst
  pdf_xml_attachment/__init__.py
  pdf_xml_attachment/__manifest__.py
  pdf_xml_attachment/i18n/es.po
  pdf_xml_attachment/i18n/hr.po
  pdf_xml_attachment/i18n/it.po
  pdf_xml_attachment/i18n/pdf_helper.pot
  pdf_xml_attachment/models/__init__.py
  pdf_xml_attachment/models/helper.py
  pdf_xml_attachment/pyproject.toml
  pdf_xml_attachment/readme/CONTRIBUTORS.md
  pdf_xml_attachment/readme/DESCRIPTION.md
  pdf_xml_attachment/readme/USAGE.md
  pdf_xml_attachment/static/description/icon.png
  pdf_xml_attachment/static/description/index.html
  pdf_xml_attachment/tests/__init__.py
  pdf_xml_attachment/tests/fixtures/pdf_with_xml_test.pdf
  pdf_xml_attachment/tests/test_helper.py
  pdf_xml_attachment/utils.py
Labels: approved, bot is merging ⏳

#1030 [17.0][IMP] base_comment_template: Allow creation of global templates
  base_comment_template/models/base_comment_template.py
  base_comment_template/models/comment_template.py
  base_comment_template/models/res_partner.py
  base_comment_template/tests/test_base_comment_template.py
  base_comment_template/views/base_comment_template_view.xml
Labels: bot is merging ⏳
